### ISSUE TITLE
Lock topic bug!

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#2218] opened 2015-10-04 14:21 UTC
Not totally sure, but i have experienced a bug on my forums.

While using quick_reply option to reply, you will see "Close Thread " button unticked.
Tick it &amp; reply, your thread will not get locked.

Website: freesamp.net

Original thread: [Lock topic bug!](http://community.mybb.com/thread-182790.html)

**Comment by Devilshakerz** [comment] 2015-10-04 15:14
Duplicate of #2022

**Closed** 2015-10-04 15:14 UTC
Labels: s:duplicate
