### ISSUE TITLE
AdminCP cannot save and apply Group Promotions - Time Registered Type

### ISSUE THREAD

**Issue by yapning** [mybb/mybb#2701] opened 2017-03-15 05:12 UTC
On MyBB 1.8.6 AdminCP, cannot save and apply Group Promotions - Time Registered Type Hours/Weeks/Months/Years.  It will always run as Days.

**Comment by PaulBender** [comment] 2017-03-15 18:24
Duplicate of #2629

**Closed by PaulBender** 2017-03-15 18:24 UTC
