### ISSUE TITLE
Creating a new post, replying and deleting it -> Integrity constraint viol...

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#262] opened 2014-03-03 19:45 UTC
> Whenever I create a new post I get these errors in the apache errorlog (also when I reply to it or delete it).
> 
> This is when creating the post:  
> PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE<sup>[23000](#fn23000)</sup>: Integrity constraint violation: 19 column dateline is not unique' in /var/www/forums/mybb/inc/db_pdo.php:67  
> Stack trace:  
> # 0 /var/www/forums/mybb/inc/db_pdo.php(67): PDO->query('UPDATE mybb_sta...', 4)
> 
> [#1](http://dev.mybb.com/issues/1) /var/www/forums/mybb/inc/db_sqlite.php(189): dbpdoEngine->query('UPDATE mybb_sta...')  
> [#2](http://dev.mybb.com/issues/2) /var/www/forums/mybb/inc/db_sqlite.php(683): DB_SQLite->query('UPDATE mybb_sta...')  
> [#3](http://dev.mybb.com/issues/3) /var/www/forums/mybb/inc/db_sqlite.php(982): DB_SQLite->update_query('stats', Array, NULL)  
> [#4](http://dev.mybb.com/issues/4) /var/www/forums/mybb/inc/functions.php(1831): DB_SQLite->replace_query('stats', Array, 'dateline')  
> [#5](http://dev.mybb.com/issues/5) /var/www/forums/mybb/inc/functions.php(1937): update_stats(Array)  
> [#6](http://dev.mybb.com/issues/6) /var/www/forums/mybb/inc/datahandlers/post.php(1441): update_forum_counters('2', Array)  
> [#7](http://dev.mybb.com/issues/7) /var/www/forums/mybb/newthread.php(397): PostDataHandler->insert_thread()  
> [#8](http://dev.mybb.com/issues/8) {main}  
>  thrown in /var/www/forums/mybb/inc/db_pdo.php on line 67, referer: [https://private-server:13443/mybb/newthread.php?fid=2](https://private-server:13443/mybb/newthread.php?fid=2)
> 
> This is when replying to that post:  
> PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE<sup>[23000](#fn23000)</sup>: Integrity constraint violation: 19 column dateline is not unique' in /var/www/forums/mybb/inc/db_pdo.php:67  
> Stack trace:  
> # 0 /var/www/forums/mybb/inc/db_pdo.php(67): PDO->query('UPDATE mybb_sta...', 4)
> 
> [#1](http://dev.mybb.com/issues/1) /var/www/forums/mybb/inc/db_sqlite.php(189): dbpdoEngine->query('UPDATE mybb_sta...')  
> [#2](http://dev.mybb.com/issues/2) /var/www/forums/mybb/inc/db_sqlite.php(683): DB_SQLite->query('UPDATE mybb_sta...')  
> [#3](http://dev.mybb.com/issues/3) /var/www/forums/mybb/inc/db_sqlite.php(982): DB_SQLite->update_query('stats', Array, NULL)  
> [#4](http://dev.mybb.com/issues/4) /var/www/forums/mybb/inc/functions.php(1831): DB_SQLite->replace_query('stats', Array, 'dateline')  
> [#5](http://dev.mybb.com/issues/5) /var/www/forums/mybb/inc/functions.php(1937): update_stats(Array)  
> [#6](http://dev.mybb.com/issues/6) /var/www/forums/mybb/inc/datahandlers/post.php(1001): update_forum_counters('2', Array)  
> [#7](http://dev.mybb.com/issues/7) /var/www/forums/mybb/newreply.php(483): PostDataHandler->insert_post()  
> [#8](http://dev.mybb.com/issues/8) {main}  
>  thrown in /var/www/forums/mybb/inc/db_pdo.php on line 67, referer: [https://private-server:13443/mybb/newreply.php?tid=1&processed=1](https://private-server:13443/mybb/newreply.php?tid=1&processed=1)
> 
> This is when deleting my reply again:  
> PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE<sup>[23000](#fn23000)</sup>: Integrity constraint violation: 19 column dateline is not unique' in /var/www/forums/mybb/inc/db_pdo.php:67  
> Stack trace:  
> # 0 /var/www/forums/mybb/inc/db_pdo.php(67): PDO->query('UPDATE mybb_sta...', 4)
> 
> [#1](http://dev.mybb.com/issues/1) /var/www/forums/mybb/inc/db_sqlite.php(189): dbpdoEngine->query('UPDATE mybb_sta...')  
> [#2](http://dev.mybb.com/issues/2) /var/www/forums/mybb/inc/db_sqlite.php(683): DB_SQLite->query('UPDATE mybb_sta...')  
> [#3](http://dev.mybb.com/issues/3) /var/www/forums/mybb/inc/db_sqlite.php(982): DB_SQLite->update_query('stats', Array, NULL)  
> [#4](http://dev.mybb.com/issues/4) /var/www/forums/mybb/inc/functions.php(1831): DB_SQLite->replace_query('stats', Array, 'dateline')  
> [#5](http://dev.mybb.com/issues/5) /var/www/forums/mybb/inc/functions.php(1937): update_stats(Array)  
> [#6](http://dev.mybb.com/issues/6) /var/www/forums/mybb/inc/class_moderation.php(512): update_forum_counters('2', Array)  
> [#7](http://dev.mybb.com/issues/7) /var/www/forums/mybb/inc/functions.php(2140): Moderation->delete_post(2)  
> [#8](http://dev.mybb.com/issues/8) /var/www/forums/mybb/editpost.php(255): delete_post(2, '1')  
> [#9](http://dev.mybb.com/issues/9) {main}  
>  thrown in /var/www/forums/mybb/inc/db_pdo.php on line 67, referer: [https://private-server:13443/mybb/showthread.php?tid=1](https://private-server:13443/mybb/showthread.php?tid=1)
> 
> On all occasions the page becomes and stays blank after submitting, manually going back to the forum index shows that the "Last Post" column is not updated and says "Never" untill I rebuild the forum counters manually. The Threads and Posts columns are updated correctly however, and if I go into the forum, the posts are there, so that part does work correctly.
> 
> This is with a fresh MyBB install on a secure private server running Fedora 10.

Original report: http://dev.mybb.com/issues/1613
Reporter: Robby Ke
Status: Confirmed

**Comment by Evenprime** [comment] 2015-07-19 08:12
This issue was most likely already fixed in 1.8.0 by this commit back in August 2014: 

https://github.com/mybb/mybb/commit/a8750d3d6f0d7f2bba9e784f0c856e99e9af3b02#diff-74a71417ab34bf758bfa5b352246f98eR1087

It added the missing "where"-clause at the appropriate execution path.

**Comment by JN-Jones** [comment] 2015-07-19 08:18
Yeah, I've fixed quite a lot of SQLite bugs back then. However I never had time to recheck the remaining ones, pretty sure there are still some.

**Comment by Destroy666x** [comment] 2015-07-19 20:31
Is there anyone with a ready SQLite installation to test? If not, I'll set up one in the next few days.

**Comment by PaulBender** [comment] 2015-07-19 22:06
I set up a SQLite installation awhile ago, but I've not been able to reproduce this bug.

**Comment by JN-Jones** [comment] 2016-11-07 16:37
Looks like I accidently fixed this back in 1.8.0 so closing

**Closed by JN-Jones** 2016-11-07 16:37 UTC
Labels: 1.8, bug, s:feedback, sqlite
