### ISSUE TITLE
CHMOD URL in AdminCP

### ISSUE THREAD

**Issue by GrannyLVP** [mybb/mybb#2342] opened 2016-02-02 16:02 UTC
inc/languages/english/admin/config_settings.lang.php 
admin/modules/tools/system_health.php 

http://docs.mybb.com/HowTo_Chmod.html

This URL is dead.

**Comment by Stefan-ST** [comment] 2016-02-02 16:25
Duplicate of #1729

**Closed by Stefan-ST** 2016-02-02 16:25 UTC
