### ISSUE TITLE
Tabbed views bug in Forum Management > Edit Permissions popup

### ISSUE THREAD

**Issue by fabd** [mybb/mybb#2230] opened 2015-10-15 13:42 UTC
Context: **Admin CP** > Forums & Posts > Forum Management

When using "Edit Permissions" on more than one group, and within the same page context (the page has not been reloaded), then the tabs in the popup are no longer "tabbed" and are stacked vertically. And then, when you click "Save Permissions" it goes to a blank page with the character "

Seems to be something wonky with the popup's init code (likely the html structure that remains in the DOM, that has changed state; just guessing as I am completely unfamiliar with the code).

Work around is to reload the page before using this popup.

**Comment by Destroy666x** [comment] 2015-10-15 20:52
This is a yet another duplicate of https://github.com/mybb/mybb/issues/2199

**Closed** 2015-10-15 20:52 UTC
Labels: s:duplicate
