### ISSUE TITLE
Last Post By shows a span.

### ISSUE THREAD

**Issue by ErikThiart** [mybb/mybb#2848] opened 2017-09-22 19:46 UTC
The last post by shows a broken span when it is yesterday.
![](https://i.imgur.com/bHroiJC.png)

**Comment by Shade-** [comment] 2017-09-22 20:23
This has been fixed in #2753. I could not reproduce your issue on a fresh 1.8.12 copy with the aforementioned patch applied. It seems like you are using a custom theme, since the patch contains changes to stylesheets you may look for them and apply them to your custom theme.

**Comment by ErikThiart** [comment] 2017-09-22 22:40
What changes in the stylesheet needs to change?

**Comment by Shade-** [comment] 2017-09-22 22:41
https://github.com/mybb/mybb/pull/2753/files#diff-05b404fc75b0e5bd6d57c79b667b44b8R794

**Closed** 2017-09-23 19:57 UTC
