### ISSUE TITLE
Post preview and editor source mode

### ISSUE THREAD

**Issue by andrewjs18** [mybb/mybb#2673] opened 2017-02-18 21:41 UTC
1.8.10 

If you check the box "Put the editor in source mode by default" in other options it causes a problem with Post Preview.

Option checked the preview jumps back to the editor after 1 second.

Option unchecked the preview stays where it should.

It's doing it on the MyBB community forum so it's easy to check.

Original thread: [Post preview and editor source mode](https://community.mybb.com/thread-208402.html)

**Comment by Shade-** [comment] 2017-02-28 14:11
This is likely caused by SCEditor focusing automatically on the source mode textarea.

**Comment by martec** [comment] 2017-09-09 03:47
I believe that sceditor already fixed, but this fix for SCEditor 2.0 https://github.com/samclarke/SCEditor/issues/456, so need wait of release of 2.0.

**Comment by Cu8eeeR** [comment] 2017-09-11 14:30
Yes, it is related to SCEditor (I use CKeditor from martec and it works fine; btw thank you!). Maybe it would be nice to send a list of all issues with SCEditor in MyBB software to SCeditor dev.

@samclarke

**Comment by effone** [comment] 2018-05-09 05:09
So, what to do with this now?
We can just comment out `sourceEditor.focus();` in SCEditor. I know its not good editing third party dependencies but can't think of any workaround.

**Comment by Eldenroot** [comment] 2018-05-10 16:38
I checked SCeditor repo briefly for new changes - I am aware that almost none of the reported bugs (maybe one or two minor) were fixed. All important bugs will be fixed in release v2.2 according to the milestone. I think that SCeditor is quite dead unfortunately, so should be replaced in MyBB v1.9 with something more viable :(

**Comment by effone** [comment] 2018-06-05 22:29
A little visual jump is not a big deal considering nothing is malfunctioning and / or breaking at MyBB part. This little odd (can't even consider this as issue) behavior belongs to third party. I believe we should close this issue as we can't do anything even we know where exactly the fault is.

**Comment by effone** [comment] 2018-07-27 01:42
Worthless fixing this - editor gonna change anyway...

**Closed by effone** 2018-07-27 01:42 UTC
Labels: 1.8, bug, s:confirmed, wontfix
