### ISSUE TITLE
Moving unapproved threads

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#270] opened 2014-03-03 19:45 UTC
> Unapprove a thread with several posts, move it to another forum and then approve it. Then the counters will be wrong (e.g. negative). This may affect only PgSQL.

Original report: http://dev.mybb.com/issues/1439
Reporter: Stefan T.
Status: Confirmed

**Comment by PaulBender** [comment] 2015-05-30 22:51
I cannot reproduce any counter issues with the latest code.

**Comment by JN-Jones** [comment] 2016-11-07 16:42
Nothing wrong here so closing (tested with the newest github code and at all stages the counters were correct)

**Closed by JN-Jones** 2016-11-07 16:42 UTC
Labels: 1.8, bug, s:feedback
