### ISSUE TITLE
Mark forum read doesn't work with php 8.0

### ISSUE THREAD

**Issue by stryderunknown** [mybb/mybb#4530] opened 2022-04-01 02:00 UTC
I just did a test upgrade to php 8.0 (while running 1.8.30) and while a majority of things seemed to work, the Mark Forums Read (from the bottom of the main index) didn't.  Reverting back to php 7.4 and it works again, so there is something buried in the code that isn't compatible.  I thought I would mention it so it can be found before 8.0 gets full support.

**Comment by dvz** [comment] 2022-04-05 14:16
Are any [errors logged](https://docs.mybb.com/1.8/faq/errors/#enabling-error-logs) when that happens?

**Comment by stryderunknown** [comment] 2022-04-05 19:22
There are plenty of errors logged for 8.0, although none of them specifically state "Mark thread Read".  
A number of undefined variables shown below. 

< error>
< dateline>1648765705</dateline>
< script>global.php(978) : eval()'d code</script>
< line>20</line>
< type>2</type>
< friendly_type>Warning</friendly_type>
  	< message>Undefined variable $menu_help</message>
  	< back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
  #1  errorHandler->error_callback() called at [/global.php(978) : eval()'d code:20]
  #2  eval() called at [/global.php:978]
  #3  require_once() called at [/showthread.php:28]
  < /back_trace>
  < /error>

 
 < error>
 	<dateline>1648765705</dateline>
 	<script>global.php(978) : eval()'d code</script>
 	<line>39</line>
 	<type>2</type>
 	<friendly_type>Warning</friendly_type>
 	<message>Undefined variable $unreadreports</message>
 	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
 #1  errorHandler->error_callback() called at [/global.php(978) : eval()'d code:39]
 #2  eval() called at [/global.php:978]
 #3  require_once() called at [/showthread.php:28]
 < /back_trace>
 < /error>
 
 < error>
 	< dateline>1648765705</dateline>
 	< script>global.php</script>
 	< line>1087</line>
 	< type>2</type>
 	< friendly_type>Warning</friendly_type>
 	< message>Undefined array key "fid4"</message>
 	< back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
 #1  errorHandler->error_callback() called at [/global.php:1087]
 #2  require_once() called at [/showthread.php:28]
 < /back_trace>
 < /error>
 
 < error>
 	<dateline>1648765705</dateline>
 	<script>showthread.php(1617) : eval()'d code</script>
 	<line>46</line>
 	<type>2</type>
 	<friendly_type>Warning</friendly_type>
 	<message>Undefined property: MyLanguage::$thread_modes</message>
 	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
 #1  errorHandler->error_callback() called at [/showthread.php(1617) : eval()'d code:46]
 #2  eval() called at [/showthread.php:1617]
 </back_trace>
 < /error>
 
 < error>
 	< dateline>1648765705</dateline>
 	< script>showthread.php(1617) : eval()'d code</script>
 	< line>61</line>
 	< type>2</type>
 	< friendly_type>Warning</friendly_type>
 	< message>Undefined variable $search_thread</message>
 	< back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
 #1  errorHandler->error_callback() called at [/showthread.php(1617) : eval()'d code:61]
 #2  eval() called at [/showthread.php:1617]
 < /back_trace>
 < /error>
 
 < error>
 	< dateline>1648765705</dateline>
 	< script>showthread.php(1617) : eval()'d code</script>
 	< line>90</line>
 	< type>2</type>
 	< friendly_type>Warning</friendly_type>
 	< message>Undefined variable $forumjump</message>
 	< back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
 #1  errorHandler->error_callback() called at [/showthread.php(1617) : eval()'d code:90]
 #2  eval() called at [/showthread.php:1617]
 < /back_trace>
 < /error>

The Undefined 'fid4' entry refers to a conditional I had originally in globals for an additional template.  Thats no longer applied, but I thought I would mention it so you can see what the error was refering to.

(below is what I had entered in global at one point)
`/* header_tracking conditional */
if($mybb->user['fid4']!='Disallow'){
eval('$header_tracking = "'.$templates->get('header_tracking').'";');
}`

Hopefully the information is of use to you.  (Edit: Added space in arrow brackets so it formats better than just being a bundle of lines)

**Comment by yuliu** [comment] 2022-12-15 17:19
I can't reproduce the "mark forum read" issue and the given error logs don't have anything related to it.

Warnings about undefined variables `$menu_help`, `$unreadreports` and `$thread_modes` probably are generated by plugins or custom theme/templates, which are not vanilla MyBB's.

Warnings about undefined variables `$search_thread` and `$forumjump` will be fixed shortly.

**Comment by Amseog** [comment] 2023-01-06 14:14
I have also encountered this issue in my own MyBB (version 1.8.33, PHP version 8.0 or 8.1 (checked both), MySQLi 5.7.38).

In order to rule out any problems with plugins or themes, I just installed a completely new and fresh, clean MyBB at https://jpstein.de/probeboard/

The problem is still there.
**Guests** can use both the "Mark this forum as read" as well as the "Mark all forums as read" functions; similarly, after reading all new threads, forums are correctly marked as fully read for guests. For **logged-in users**, however, none of these things work anymore.
Strangely enough, I was able to completely remedy this error by exchanging the word "shutdown_query" with "write_query" in the PHP file "inc/function_indicators.php"...but I am not very experienced, and believe that this is just a dirty hack. :)

Here's the error log: 
https://jpstein.de/probeboard/error.log

PS: My clean MyBB install also shows another problem since upgrading to PHP 8.0, but I will open a separate issue for this to keep the GitHub orderly.
PPS: Thank you so much, yuliu, for your work and efforts.

**Comment by yuliu** [comment] 2023-01-06 15:01
> (...)
> 
> The problem is still there. **Guests** can use both the "Mark this forum as read" as well as the "Mark all forums as read" functions; similarly, after reading all new threads, forums are correctly marked as fully read for guests. For **logged-in users**, however, none of these things work anymore. Strangely enough, I was able to completely remedy this error by exchanging the word "shutdown_query" with "write_query" in the PHP file "inc/function_indicators.php"...but I am not very experienced, and believe that this is just a dirty hack. :)
> 
> Here's the error log: https://jpstein.de/probeboard/error.log

From the error log you've linked, the "Mark ... as read" function doesn't work under PHP 8 may be caused by the builtin function `sys_getloadavg()` not working as expected:
```
Trying to access array offset on value of type bool

#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/inc/functions.php:2710]
#2  get_server_load() called at [/inc/functions.php:45]
#3  output_page() called at [/inc/functions.php:1097]
#4  redirect() called at [/misc.php:99]
```
Although I'm not sure if this warning would prevent from running `run_shutdown()`.

A related issue is #4629.

**Comment by dvz** [comment] 2023-01-06 16:53
Indeed, the code at https://github.com/mybb/mybb/blob/59bce8d47cb3848d4f6be18d8114d1d298f65c88/inc/functions.php#L2708-L2710 doesn't take `false` into account (https://www.php.net/manual/en/function.sys-getloadavg.php).

This results in a PHP Warning with [PHP 8.0](https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.core.other) (previously, a Notice - [ignored by MyBB's error handler](https://github.com/mybb/mybb/blob/f268841e760a1fc34e6e2a8b58b647079f2a1a07/inc/class_error.php#L101) - was generated):
> A number of notices have been converted into warnings:
> [...]
> - Attempting to access an array index of a non-array.


The PHP Warning, when picked up by MyBB's error handler, causes `errorHandler::$has_errors` to be set to `true` at https://github.com/mybb/mybb/blob/962212ecf5fd84a198daea562b1124c4ba89c933/inc/class_error.php#L183

which then prevents shutdown functions and queries from running, as a result of the check at
https://github.com/mybb/mybb/blob/962212ecf5fd84a198daea562b1124c4ba89c933/inc/functions.php#L145-L148

Similar problem occurred in: https://github.com/mybb/mybb/issues/2665#issuecomment-282886253, https://community.mybb.com/thread-233580-post-1377093.html#pid1377093

So there's also a separate question of whether any problems picked up by MyBB's error handler should prevent shutdown functions from running.

**Comment by avs-code** [comment] 2023-01-11 14:09
Versión de MyBB | 1.8.33
Motor SQL | MySQLi 5.7.40
Versión PHP | 8.0.26

My log:
```
<error>
	<dateline>1673446018</dateline>
	<script>global.php(958) : eval()'d code</script>
	<line>33</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined array key "use_xmlhttpsrequest"</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/global.php(958) : eval()'d code:33]
#2  eval() called at [/global.php:958]
#3  require_once() called at [/forumdisplay.php:24]
</back_trace>
</error>

<error>
	<dateline>1673446018</dateline>
	<script>inc/functions_forumlist.php</script>
	<line>447</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined property: MyLanguage::$expcol_collapse</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/inc/functions_forumlist.php:447]
#2  build_forumbits() called at [/forumdisplay.php:154]
</back_trace>
</error>

<error>
	<dateline>1673446018</dateline>
	<script>inc/functions_forumlist.php</script>
	<line>447</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined property: MyLanguage::$expcol_collapse</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/inc/functions_forumlist.php:447]
#2  build_forumbits() called at [/forumdisplay.php:154]
</back_trace>
</error>

<error>
	<dateline>1673446018</dateline>
	<script>inc/functions_forumlist.php</script>
	<line>447</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined property: MyLanguage::$expcol_collapse</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/inc/functions_forumlist.php:447]
#2  build_forumbits() called at [/forumdisplay.php:154]
</back_trace>
</error>

<error>
	<dateline>1673446018</dateline>
	<script>inc/functions_forumlist.php</script>
	<line>447</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined property: MyLanguage::$expcol_collapse</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/inc/functions_forumlist.php:447]
#2  build_forumbits() called at [/forumdisplay.php:154]
</back_trace>
</error>

<error>
	<dateline>1673446018</dateline>
	<script>forumdisplay.php(746) : eval()'d code</script>
	<line>13</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined property: MyLanguage::$ratings_update_error</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/forumdisplay.php(746) : eval()'d code:13]
#2  eval() called at [/forumdisplay.php:746]
</back_trace>
</error>

<error>
	<dateline>1673446019</dateline>
	<script>global.php(958) : eval()'d code</script>
	<line>33</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined array key "use_xmlhttpsrequest"</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/global.php(958) : eval()'d code:33]
#2  eval() called at [/global.php:958]
#3  require_once() called at [/forumdisplay.php:24]
</back_trace>
</error>

<error>
	<dateline>1673446019</dateline>
	<script>forumdisplay.php(746) : eval()'d code</script>
	<line>13</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined property: MyLanguage::$ratings_update_error</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/forumdisplay.php(746) : eval()'d code:13]
#2  eval() called at [/forumdisplay.php:746]
</back_trace>
</error>

<error>
	<dateline>1673446019</dateline>
	<script>forumdisplay.php(1546) : eval()'d code</script>
	<line>60</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined variable $forumjump</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/forumdisplay.php(1546) : eval()'d code:60]
#2  eval() called at [/forumdisplay.php:1546]
</back_trace>
</error>

<error>
	<dateline>1673446021</dateline>
	<script>global.php(958) : eval()'d code</script>
	<line>33</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined array key "use_xmlhttpsrequest"</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/global.php(958) : eval()'d code:33]
#2  eval() called at [/global.php:958]
#3  require_once() called at [/showthread.php:28]
</back_trace>
</error>

<error>
	<dateline>1673446021</dateline>
	<script>showthread.php(797) : eval()'d code</script>
	<line>5</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined property: MyLanguage::$ratings_update_error</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/showthread.php(797) : eval()'d code:5]
#2  eval() called at [/showthread.php:797]
</back_trace>
</error>

<error>
	<dateline>1673446021</dateline>
	<script>showthread.php(1617) : eval()'d code</script>
	<line>90</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined variable $forumjump</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/showthread.php(1617) : eval()'d code:90]
#2  eval() called at [/showthread.php:1617]
</back_trace>
</error>

<error>
	<dateline>1673446023</dateline>
	<script>global.php(958) : eval()'d code</script>
	<line>33</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined array key "use_xmlhttpsrequest"</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/global.php(958) : eval()'d code:33]
#2  eval() called at [/global.php:958]
#3  require_once() called at [/showthread.php:28]
</back_trace>
</error>

<error>
	<dateline>1673446023</dateline>
	<script>showthread.php(797) : eval()'d code</script>
	<line>5</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined property: MyLanguage::$ratings_update_error</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/showthread.php(797) : eval()'d code:5]
#2  eval() called at [/showthread.php:797]
</back_trace>
</error>

<error>
	<dateline>1673446023</dateline>
	<script>showthread.php(1617) : eval()'d code</script>
	<line>90</line>
	<type>2</type>
	<friendly_type>Warning</friendly_type>
	<message>Undefined variable $forumjump</message>
	<back_trace>#0  errorHandler->error() called at [/inc/class_error.php:153]
#1  errorHandler->error_callback() called at [/showthread.php(1617) : eval()'d code:90]
#2  eval() called at [/showthread.php:1617]
</back_trace>
</error>
```

**Closed as completed** 2023-04-18 17:13 UTC
Labels: t:bug, b:1.8, s:resolved
