### ISSUE TITLE
1.8.27 - saving attachment edit page results in database error due to missing column

### ISSUE THREAD

**Issue by RzNmKX** [mybb/mybb#4449] opened 2021-09-06 15:38 UTC
Seems like a column is missing in the database. This is a very fresh install, installed on 2021-09-04, version 1.8.27.

Admin CP -> Attachment Types -> from any type -> options -> edit -> save attachment type.

```
SQL Error:
    1054 - Unknown column 'forcedownload' in 'field list'
Query:
    UPDATE mybb_attachtypes SET `name`='Bitmap Image', `mimetype`='image/bmp', `extension`='bmp', `maxsize`=500, `icon`='images/attachtypes/image.png', `enabled`=1, `forcedownload`=0, `groups`='-1', `forums`='-1', `avatarfile`=0 WHERE atid='16' 
```

```
MariaDB [mybb]> describe mybb_attachtypes;
+------------+------------------+------+-----+---------+----------------+
| Field      | Type             | Null | Key | Default | Extra          |
+------------+------------------+------+-----+---------+----------------+
| atid       | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name       | varchar(120)     | NO   |     |         |                |
| mimetype   | varchar(120)     | NO   |     |         |                |
| extension  | varchar(10)      | NO   |     |         |                |
| maxsize    | int(15) unsigned | NO   |     | 0       |                |
| icon       | varchar(100)     | NO   |     |         |                |
| enabled    | tinyint(1)       | NO   |     | 1       |                |
| groups     | text             | NO   |     | NULL    |                |
| forums     | text             | NO   |     | NULL    |                |
| avatarfile | tinyint(1)       | NO   |     | 0       |                |
+------------+------------------+------+-----+---------+----------------+
10 rows in set (0.000 sec)
```

Commenting out lines 92 and 380 in /admin/modules/config/attachment_types.php solves the issue temporarily.

**Comment by euantorano** [comment] 2021-09-06 16:09
This field is in the `upgrade52` upgrade script: https://github.com/mybb/mybb/blob/feature/install/resources/upgrade52.php#L48

It's also in the `mysql_db_tables` resource: https://github.com/mybb/mybb/blob/feature/install/resources/mysql_db_tables.php#L106

We'll have to try and reproduce this to work out how it's possible to end up without this column, as it's not immediately obvious to me.

**Comment by dvz** [comment] 2021-09-06 16:13
Duplicate of #4423

**Closed as completed by dvz** 2021-09-06 16:13 UTC
Labels: s:duplicate
