### ISSUE TITLE
Warning System - small bug in warning log

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#3470] opened 2018-10-14 14:29 UTC
In my forum, I have a warning type that is basically a "first warning". It is just logged as such but doesn't add warning points (set to 0). That works nicely everywhere BUT in one place: In ACP &gt; Tools &amp; Maintenance &gt; User Warning Log, it lists these warnings with "(+50)" as if the user had been given the Maximum Warning Points (100%) set in configuration &gt; warning system settings. 
It is merely a cosmetic issue, but it's still bugging me because it looks in the logs as if the least offense got the highest penalty.

Original thread: [Warning System - small bug in warning log](https://community.mybb.com/thread-220210.html)

**Comment by AndreRl** [comment] 2018-10-29 20:07
@euantorano Correct me if I'm wrong, but by default MyBB requires the warning type to have a point greater than 0, therefore, this would of been a database edit which we possibly can't support.

@Eldenroot Can you give steps to reproduce? I can't reproduce this without making a database edit.

**Comment by linguisten** [comment] 2018-11-03 21:52
No, i created that warning in the ACP only, not by database edit.

**Comment by Ben-MyBB** [comment] 2020-06-11 14:55
I have been trying to test this and if you set 0 for warning points value in the ACP then you are thrown an error as invalid value. @Eldenroot ?

**Comment by JordanMussi** [comment] 2020-06-11 15:17
@Ben-MyBB just checked and it is possible to edit a warning type to set it to 0. The `<= 0` condition was only added for create in #773.

So that needs to be fixed. Not sure about this log display issue since points of 0 should not have been allowed 🤔

**Comment by Ben-MyBB** [comment] 2020-06-11 15:23
IMHO we should just set the validation on the edit field. I don’t think a large amount of users have done this since there has been no support threads etc except this one, IIRC.

**Comment by JordanMussi** [comment] 2020-06-11 16:54
Done a PR with both for you @Ben-MyBB #4064

**Comment by Eldenroot** [comment] 2020-06-11 16:56
Great! Now we just need a spare @euantorano to merge all these PRs :)

**Comment by Ben-MyBB** [comment] 2020-06-11 16:58
> 
> 
> Great! Now we just need a spare @euantorano to merge all these PRs :)

Most of these will be going in to 1.8.24. There's a few outstanding PR's for 1.8.23 that we are looking to include.

**Comment by Eldenroot** [comment] 2020-06-11 16:59
I understand, we need to merge PRs related to attachments from Laird... at least to 1.8.23

**Comment by euantorano** [comment] 2020-06-11 17:59
Yes, that is the one I’m currently testing and hoping to merge today, along with reCAPTCHA v3.

**Comment by yuliu** [comment] 2020-06-12 06:10
The logs will say some _random_ values for a warning type that has a `0` warning point just because `$points` might be from previous returned data row.

https://github.com/mybb/mybb/blob/9feef312dc22abef36dcc1ddb1a703e66d9c2fe1/admin/modules/tools/warninglog.php#L432

I personally would use a warning type with `0` warning point. Anyway, enforcing the warning point to be greater than 0 is OK.

**Comment by JordanMussi** [comment] 2020-06-12 15:35
The decision to enforce > 0 was already made previously. The PR just ensures it is properly enforced. Do we think we should reverse it and allow 0 point warnings?

**Comment by yuliu** [comment] 2020-06-12 16:49
We don't need to reverse it if there's no such demand.

I was just thinking it might be useful in some circumstances for forum admins to give a user some warning without really adding warning points.

> Btw the warnings table in User CP is not displayed when the user has only been given a warning of 0 points so that will need changing too if so.

If that's the case, it'll be good to get fixed in the PR.

**Comment by JordanMussi** [comment] 2020-06-12 19:25
> If that's the case, it'll be good to get fixed in the PR.

I think it is designed to disappear when the user hasn't got any non expired warnings (current warning level = 0). But there's an argument that the latest warnings should be shown if there are any even if they've expired 

https://github.com/mybb/mybb/blob/36e8e7167c693ad0ac78dd05406e4cfa8fe0a9eb/usercp.php#L4088-L4107

We'd need a different way to tell if there are "recent" warnings than just using the warning level if it were to be changed.

**Closed** 2020-06-30 19:43 UTC
Labels: b:1.8, s:review-needed, t:bug
