### ISSUE TITLE
Double Banned Bug

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#266] opened 2014-03-03 19:45 UTC
> This is a weird bug to report, but here's how to reproduce. Note this is confirmed on MyBB.com and in a local environment.
> 
> Reproduction Steps:  
> 1) Create a second banned usergroups, that can access the forums and acts as a banned group.  
> 2) Go to the ModCP and give a ban to this usergroup, making sure he goes to the new usergroup.  
> 3) Now give a warning to this user, making sure it hits a specific warning level and auto bans.  
> 4) Go to the ModCP and click Lift Ban on one of the 2 entries.  
> 5) Log in as this user and the bug will appear.
> ## 
> 
> In addition, when you lift one of the two ban entries, it removes both of them.

Original report: http://dev.mybb.com/issues/1557
Reporter: Ichibi no Shukaku
Status: Confirmed

**Comment by Naththo** [comment] 2015-02-19 16:28
I can't seem to reproduce this..

**Comment by Sama34** [comment] 2015-02-20 06:46
I think this may be only true if the user mess with the `Can receive warnings from other users?` group setting.

If it is set to true for all banned groups then the user cannot be warned/banned if it belongs to any already.

**Comment by PaulBender** [comment] 2015-05-30 23:08
I can confirm this bug still exists.

**Comment by wlisik** [comment] 2017-11-03 11:44
Also confirming it.....

**Comment by AndreRl** [comment] 2018-06-03 12:31
I am unable to reproduce the bug displayed to the previously banned user in the latest version (1.8.15). Although, a user shouldn't be banned again (and moved to the new ban group) if they're already banned. Either an error should be thrown or the current warning will be updated instead.

**Comment by Ben-MyBB** [comment] 2018-06-08 19:53
@effone have you had a chance to investigate this at all?

**Comment by effone** [comment] 2018-06-09 06:17
Nope, I'll look at it. OK.

**Comment by Azareal** [comment] 2018-06-11 08:32
I can see how you might be able to do it with a data race, but it takes some luck to get two mods to act on one user at the same time. As for sequentially, it sounds as if there's a check somewhere which isn't quite as water-tight as you think or something else missing.

**Comment by effone** [comment] 2018-06-12 07:31
As on date, with 1.8.15, I can't warn a banned user. There is no link remained for warn after ban.
Manual attempt prevented me to place the warn, though the message was misleading: `You do not have permission to warn users of this group.`

This report is not valid as on date, I guess ...

**Comment by effone** [comment] 2018-08-14 09:03
Closing this til further report. If anyone can reproduce this still now please reopen the issue with updated reproduction steps.

**Closed by effone** 2018-08-14 09:03 UTC
Labels: 1.8, bug
