### ISSUE TITLE
Last Post permissions failing for Subforum

### ISSUE THREAD

**Issue by PirataNervo** [mybb/mybb#2354] opened 2016-03-04 13:50 UTC
Go to: http://forums.mybb-plugins.com/

See the "Custom Plugins" forum. You can see the last post is most of the times from the sub forum "Quotes and Discussion" forum. If you open the Custom Plugins forum, you see that you can't see the last posts from that sub forum. But on the index, you can !

Basically, the "View Own Threads" doesn't seem to be checked.

**Comment by Destroy666x** [comment] 2016-03-04 19:41
Actually, I can't reproduce on 1.8.6. Maybe you made the same mistake as me and tested as guest while only the registered group had that option enabled.

**Comment by PirataNervo** [comment] 2016-03-08 13:48
The problem is actually for Guests. The option is enabled for all groups except Admins. So no one, including guests, should see other people's last posts. What seems to be the problem is that for subforums (when getting the last post of the main forum), it doesn't check that permission (or does so incorrectly). Because when viewing the list of sub forums and their last posts, it works fine. The problem is the last post of the parent forum, when sub forums have newer threads.

**Comment by Destroy666x** [comment] 2016-03-08 15:48
As I said, I can't reproduce.
1. Created a forum and subforums, subforum has "only own" permission enabled for everyone except admins, parent not.
2. Posted as an admin in both forums, first in parent, then in child.
3. Logged off and I see the thread in parent forum as last post.

Please try on a clean 1.8.6 forum and with this PR merged: https://github.com/mybb/mybb/commit/1cd8126a4f36119d1e6cea8a5d8861fe5cb00780.

**Comment by Destroy666x** [comment] 2016-03-08 15:54
As I said, I can't reproduce. I:
1. Created a parent forum and its child forum, the child forum has "only own" permission for everyone except admins.
2. Posted as an admin, first in the parent forum, then in the child forum.
3. Logged off and there's the thread from the parent forum in last post info.

Please test on a clean 1.8.6 and with this 1.8.7 PR merged (which may have also fixed this): https://github.com/mybb/mybb/commit/1cd8126a4f36119d1e6cea8a5d8861fe5cb00780.

**Comment by PirataNervo** [comment] 2016-03-12 18:04
I've just upgraded to MyBB 1.8.7 and the issue seems to be gone. Not sure if it was that PR or not but it's definitely fixed :)

**Comment by Destroy666x** [comment] 2016-03-12 18:17
Closing then

**Closed by Destroy666x** 2016-03-12 18:17 UTC
Labels: 1.8, bug, p:normal, s:feedback
