### ISSUE TITLE
Can't install MyBB on MySQL 8

### ISSUE THREAD

**Issue by alexantr** [mybb/mybb#3382] opened 2018-08-08 14:34 UTC
Words "group" and "admin" [reserved](https://dev.mysql.com/doc/refman/8.0/en/keywords.html) since 8.0 version.

Need to escape column names with backtick sign:

like `` `admin` int unsigned NOT NULL default '0',``

---

![q5fukqh](https://user-images.githubusercontent.com/4941848/43843686-ca321cea-9b30-11e8-808a-831cd4d17b89.png)

After `mysql_db_tables.php` was edited manually got next portions of errors:

![irafbam](https://user-images.githubusercontent.com/4941848/43843594-9b51ef9a-9b30-11e8-9d8e-1d0b36803a11.png)

**Comment by kawaii** [comment] 2018-08-08 14:46
Closing this issue as a duplicate of #2921.

It will be fixed in MyBB 1.9, although that fix is unlikely to make it into the 1.8 series unfortunately.

**Closed by kawaii** 2018-08-08 14:46 UTC
