### ISSUE TITLE
Reply button with usernames containing quotes

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb#1774] opened 2015-01-18 22:19 UTC
When using the reply button to quote a post, the quote MyCode inserted in the editor is wrong if the quoted user has an apostrophe in their username.

**Example:** Username: "Fardel's Bear"
**Action:** Click Reply on a post by the user
**Created quote code in the full editor:**

```
[quote=Fardel pid='1' dateline='1421574511']
This is a test post for testing MyAlerts...
[/quote]
```

I've not looked at the code, but I can confirm this on a  fresh install of the current dev version of MyBB 1.8 and a live forum running 1.8.3.

Original thread: [Reply button with usernames containing quotes](http://community.mybb.com/thread-165780.html)

**Comment by euantorano** [comment] 2015-01-18 22:24
Not had a chance to test, but I think the issue is in `inc/functions_posting.php`...

**Comment by euantorano** [comment] 2015-01-18 22:34
Doing a quick bit of debug, the quote is right up until the point that it hits the WYSIWYG editor, which obviously gets confused at the double apostrophes and just strips the extra text.

**Comment by euantorano** [comment] 2015-01-18 22:41
Fix:

`inc/functions_posting.php` line 218: add before `return`:

```php
$quoted_post['username'] = addslashes($quoted_post['username']);
```

**Comment by Cu8eR** [comment] 2015-01-19 18:50
This should be fixed in MyBB 1.8.4 - because this bugs affects some plugins

**Comment by Sama34** [comment] 2015-01-20 06:02
Which plugins?

**Comment by Cu8eR** [comment] 2015-01-20 12:42
@Sama34 - for example all plugins for quick (fast) quotes

**Comment by Destroy666x** [comment] 2015-01-20 14:33
It doesn't matter that it affects plugins too.. The biggest problem which might move this issue to 1.8.4 is that it affects the core itself.

**Comment by euantorano** [comment] 2015-01-20 20:01
@Destroy666x the above fix is not complete. Unfortunately when the quote is saved, some other processing seems to happen. I haven't had a chance to look at what else is going wrong yet.

**Comment by Sama34** [comment] 2015-01-21 02:49
If this is a SCEditor issue we can probably ask the developers.

**Comment by euantorano** [comment] 2016-11-10 17:05
I had a brief look and couldn't work out where it was going wrong. I'll have a look this weekend.

**Comment by WildcardSearch** [comment] 2017-01-16 02:31
The problem is that in `functions_posting.php`'s `parse_quoted_message`, single quotes are used without checking to see if the user name contains single quotes.

**Comment by WildcardSearch** [comment] 2017-01-31 23:35
This is a simple fix. Can anyone test #2624 ?

**Closed** 2017-02-04 01:34 UTC
Labels: 1.8, bug, p:normal, s:confirmed
