### ISSUE TITLE
Sceditor smilies WYSIWYG mode, not parsed correctly.

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#2045] opened 2015-06-19 03:14 UTC
Hello,

I am new to the MyBB community, and I would like to report a bug.
I have searched if it has already been reported but did not find, so I am reporting it here.

When typing at the editor, in WYSIWYG mode, the following:
". :) q"
You will see that it will transform to:
". ::)"

Moreover, smilies' images don't always show up after typing them. For example, when typing ":)" right before any text has been inserted to the editor, it won't convert to a picture.

I have looked into this issue using Firebug console, and I got the following error (at jquery.sceditor.bbcode.min.js file):

Code:
IndexSizeError: Index or size is negative or greater than the allowed amount
&nbsp;&nbsp;&nbsp;&nbsp;

...}return g},hasStyle:function(b,c,d){var f=e.getStyle(b,c);return f?!d||f===d||a....

After replacing the jquery.sceditor.bbcode.min.js file with the jquery.sceditor.bbcode.js file provided here, the problem persisted exactly the same, however I got a more understanding javascript code this time, except I don't understand it.

This was tested at a fresh installation of MyBB 1.8.5 and right here in the Community forums while writing this report.

If anyone can find a solution I would appreciate it very much. Thanks.

Original thread: [Sceditor smilies WYSIWYG mode, not parsed correctly.](http://community.mybb.com/thread-171581.html)

**Comment by Sama34** [comment] 2015-06-19 06:10
> I am new to the MyBB community

Yeah me too >_>

**Comment by Destroy666x** [comment] 2015-06-19 06:38
> Moreover, smilies' images don't always show up after typing them. For example, when typing ":)" right before any text has been inserted to the editor, it won't convert to a picture. 

That's an intended SCEditor `emoticonCompat` option behavior... You need to enter a space before and after an emoticon so that it shows up. It's to prevent parsing for example `:/` in `http://`. Nothing we should fix, IMO.

> When typing at the editor, in WYSIWYG mode, the following:
". :) q"
You will see that it will transform to:
". ::)"

This is most likely a SCEditor bug. It also happens for other similar sequences, such as `; :) h` @samclarke @brunoais

> IndexSizeError: Index or size is negative or greater than the allowed amount

This looks like a SCEditor bug too. @samclarke @brunoais - let us know if you need more info.

**Comment by MangaD** [comment] 2015-06-19 09:36
> That's an intended SCEditor emoticonCompat option behavior... You need to enter a space before and after an emoticon so that it shows up. It's to prevent parsing for example :/ in http://. Nothing we should fix, IMO.

Have you tried going to editor and type ":) something"? It does not convert the smilie to an image, but it should. Try it in Community forums and [Sceditor website](http://www.sceditor.com/), you will see the difference...

**Comment by brunoais** [comment] 2015-06-19 10:48
@Destroy666x SCE version pls.

**Comment by JN-Jones** [comment] 2015-06-19 11:02
According to the file 1.4.7

**Comment by brunoais** [comment] 2015-06-19 15:02
I can confirm the bug

**Comment by Destroy666x** [comment] 2015-06-21 02:45
@brunoais, thanks for a quick reaction.

**Comment by Cu8eR** [comment] 2016-01-24 16:23
fixed here, not?
https://github.com/samclarke/SCEditor/commit/1bc73b156fcab291210a48bf152874095b1b5d06

**Comment by Destroy666x** [comment] 2016-01-24 19:41
It is fixed there but there's no new SCEditor version so we haven't updated it yet.

**Comment by brunoais** [comment] 2016-01-24 19:43
@samclarke is the only one who can make new versions. Unfortunately, I can't help you there.

**Comment by Cu8eR** [comment] 2016-01-24 19:43
yeah, I figured it after I wrote here... it would be nice to have a new version out before MyBB 1.8.7 because this bug is really annoying... @brunoais - could you contact him somehow?

**Comment by Sama34** [comment] 2016-05-17 19:04
I would assumed this to be closed when we update the editor, you will need to be patient @Cu8eR

**Comment by Cu8eR** [comment] 2016-05-17 19:06
Fortunately I changed this buggy editor with CKEditor from @martec. Works fine, no more reports from users... MyBB team made a bad decision with SCEditor, anyway there is a simple solution

**Comment by Sama34** [comment] 2016-05-17 19:29
We probably did, however you need to understand and accept the fact that the editor is not going to be changed in 1.8. Regardless we do appreciate your contributions, thank you.

**Comment by brunoais** [comment] 2016-05-17 19:33
I think SCE is dead because Sam is, unfortunately, dead. Otherwise it would have evolved.
Did they finally fix the BBCode parser for CKE? Last time I tried it was quite bad....

**Comment by Destroy666x** [comment] 2016-05-17 23:01
Well, it's usable in other forum scripts and unlike SCEditor it doesn't duplicate tags unnecessarily.

I still hope @samclarke didn't completely abandon the project, his stackoverflow account is still active.

**Comment by brunoais** [comment] 2016-05-18 15:32
I still strongly suspect he died.
He still won't answer my e-mails, he didn't do absolutely anything on github since July last year and his activity on stackoverflow is very suspicious as he keeps logging in without doing anything besides the actual logging in.

**Comment by Mikemayday** [comment] 2016-09-05 23:43
Hello,
I'm pretty new to MyBB (and running a forum in general) so terribly sorry if this is an obvious question. Is it possible to manually update SCEditor in your installation? This is a REALLY annoying bug and since I've just got tasked with moving a rather big community to MyBB, I don't want to disappoint.

**Comment by Cu8eR** [comment] 2016-09-06 05:02
@Mikemayday - you can replace this bugged editor with CKeditor - plugin is here: https://community.mybb.com/thread-189422.html + I recommend to use it together with dvz mentions plugin for tagging users ;)

**Comment by Mikemayday** [comment] 2016-09-06 07:56
Well, funnily enough, Rin also appears to have a problem with smilies.

If I insert a smiley via the smiley panel, it appears ok in the editor. When I click preview, the smiley looks ok in the post preview, but is broken in the wyswig editor and in the final post. Its URL gets replaced with "http://foo.bar/http"

If I insert the smiley by typing the appropriate text and then click preview, they appear okay in the preview AND the editor, but when I click preview again, the smilies are broken as above.

**Comment by Mikemayday** [comment] 2016-09-06 18:29
@Destroy666x As a failsafe, I wanted to ask: it appears @samclarke has been pushing some stuff to his main SCE branch again, do you think there's a chance for an update in MyBB?

**Comment by JN-Jones** [comment] 2016-11-10 16:01
As @samclarke is alive again and new versions have been released it'd be nice to get those updates in 1.8.9 @mybb/developers

**Comment by Eldenroot** [comment] 2019-02-18 19:09
@euantorano - I think this is fixed by new SCEditor 1.5.1, not?

**Comment by euantorano** [comment] 2019-02-18 19:13
I’m not sure, I haven’t tested that yet actually. I hope it will be though!

**Comment by effone** [comment] 2019-05-06 15:55
The smilie space-around issue appears to be intended.
The other mentioned issue seems fixed by the SCE update.
Anyone wanna recheck before closing this?

**Comment by euantorano** [comment] 2019-05-06 16:13
I will test this before we close, I will test either today or tomorrow.

**Closed** 2019-09-08 13:41 UTC
Labels: 3rdparty, b:1.8, p:low, s:confirmed, t:bug
