### ISSUE TITLE
Suspend this user's signature

### ISSUE THREAD

**Issue by Javierj12** [mybb/mybb#3802] opened 2019-09-13 15:29 UTC
Hello friends, I come again from these sides, I think I found a bug in suspending a user's signature, since when suspending this comes up:

![image](https://user-images.githubusercontent.com/53314750/64874560-4021e380-d619-11e9-989d-959192cf4f7e.png)

![image](https://user-images.githubusercontent.com/53314750/64874569-4a43e200-d619-11e9-9471-bb583aee67d1.png)

A simple one appears (Array), I do not know if there is an open problem about this, and if so I am sorry, I speak Spanish and besides that I do not have time to search, Regards

**Comment by yuliu** [comment] 2019-09-13 15:51
Which version of MyBB are you using?

Did you encounter this problem when suspending user's signature via ModCP? Or does the URL look like `https://.../modcp.php?action=editprofile&uid=...`?

Seems it's output from a plugin rather than from MyBB. Do you have any enabled plugin relating to moderation?

**Comment by Javierj12** [comment] 2019-09-14 00:12
Hello, first of all I am using it from ModCP
`forum/modcp.php?action=editprofile&uid=3`

I don't use any add-on, I use the default theme. Version 1.8.21

**Comment by yuliu** [comment] 2019-09-14 09:03
Not sure what's causing it, but looks like it's the `$errors` variable who tried to output something.

Could you please have a check on templates under `Error Message Templates` group if they've been modified. And what's the page you were at and what changes you've made on that page before you get into that screen? Well, and what's your PHP version.

**Comment by euantorano** [comment] 2019-09-14 09:07
There is a currently open PR relating to the $errors variable that may fix this issue.

**Comment by yuliu** [comment] 2019-09-14 10:03
> There is a currently open PR relating to the $errors variable that may fix this issue.

Oh, I found it. It's already merged by #3714.

So this issue might be a duplicate of #3713.

@Javierj12, a next 1.8 release will fix your problem but you may always test the latest dev build from GitHub for non-production use.

**Comment by Javierj12** [comment] 2019-09-14 14:10
Ok, thanks, hopefully in the next version it will be solved, regards

**Closed** 2019-09-15 12:00 UTC
