### ISSUE TITLE
Warning [2] urlencode() expects parameter 1 to be string, array given - Line: 4964 - File: inc/functions.php

### ISSUE THREAD

**Issue by hrubymar10** [mybb/mybb#2648] opened 2017-01-30 14:00 UTC
`Warning [2] urlencode() expects parameter 1 to be string, array given - Line: 4964 - File: inc/functions.php PHP 7.0.15-1~dotdeb+8.1 (Linux)`

Can someone please post here any workaround for this line? Should I add here some kind of variable type check? But what should I do, when given variable will be for example int?

**Comment by Stefan-ST** [comment] 2017-01-30 15:30
We do not provide support on Github. Please use our community forums instead: https://community.mybb.com/

Duplicate of #2316

**Closed by Stefan-ST** 2017-01-30 15:30 UTC
