### ISSUE TITLE
Fulltext search does not work in non-English language

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#3937] opened 2020-04-16 17:15 UTC
Hello, 
The forum in Polish language. Fulltext search option is set in the ACP Search options.

The word "tydzień" is "week" in Polish - fairly popular.

Bug: When I type in "tydzień" in the Advanced Search and search only in subject, I receive a message, that there's no search results.

Mysql fulltext seems to work,

SELECT count(*) FROM `mybb_threads` WHERE match(subject) against ('tydzień');
returns 14 entries.

When I switch to "Standard search" I do get 14 results too.

I came across this bug several times on different installations, hosts etc.

Queries with only ASCII chars work just fine between the Standard and Fulltext seach modes. They return sometimes different number of results due to the nature of the fulltext seach versus the Like '%%' query ;)

Original thread: [Fulltext search does not work in non-English language](https://community.mybb.com/thread-227328.html)

**Comment by euantorano** [comment] 2020-04-16 21:42
I wonder if this might be related to [`clean_keywords_ft`](https://github.com/mybb/mybb/blob/5b78e975976c6ed7946860dc3eeea931a767488d/inc/functions_search.php#L1406) or something. I'll try stepping through it in a debugger and see what the actually query is that gets produced - I bet there's something mangling it before running the query.

**Comment by Eldenroot** [comment] 2020-04-17 18:02
Anyway it is quite frustrating, I reported this 1 or 2 years back, as a workaround I do not use full-text search...

**Comment by euantorano** [comment] 2020-04-17 18:03
I must have missed the original report, apologies. I’m going to test this tonight and see if I can confirm my suspicion.

**Comment by Eldenroot** [comment] 2020-04-17 18:12
Never mind @euantorano :) I am looking for your conclusion :) fingers crossed!

**Comment by euantorano** [comment] 2020-04-17 22:01
Note for self in testing:

Fulltext search in MySQL has a funny quirk - if the keyword you're searching for in 50% or more of all rows and the table is using the MyISAM engine (as they do by default), no results will be returned: https://dev.mysql.com/doc/refman/8.0/en/fulltext-natural-language.html

> The search result is empty because the word “MySQL” is present in at least 50% of the rows, and so is effectively treated as a stopword. This filtering technique is more suitable for large data sets, where you might not want the result set to return every second row from a 1GB table, than for small data sets where it might cause poor results for popular terms.
>
> The 50% threshold can surprise you when you first try full-text searching to see how it works, and makes InnoDB tables more suited to experimentation with full-text searches. If you create a MyISAM table and insert only one or two rows of text into it, every word in the text occurs in at least 50% of the rows. As a result, no search returns any results until the table contains more rows. Users who need to bypass the 50% limitation can build search indexes on InnoDB tables, or use the boolean search mode explained in Section 12.9.2, “Boolean Full-Text Searches”.

In this case, use `IN BOOLEAN MODE`:

```SQL
SELECT * FROM mybb_threads WHERE match(subject) against ('tydzień' IN BOOLEAN MODE);
```

Or, change the table engine to InnoDB.

**Comment by euantorano** [comment] 2020-04-17 22:15
Ok, so `clean_keywords_ft('tydzień')` results in `+tydzie`. Running the following query returns no results (obviously):

```sql
SELECT * FROM mybb_threads WHERE match(subject) against ('+ tydzie' IN BOOLEAN MODE);
```

The problematic block of code appears to be https://github.com/mybb/mybb/blob/feature/inc/functions_search.php#L285:L289

Time to go regex fishing.

**Comment by Eldenroot** [comment] 2020-04-18 05:29
@euantorano - I use InnoDB :)

**Comment by yuliu** [comment] 2020-04-18 05:58
A warning was sent when searching with Fulltext on the redirect page, regardless of applying #3942.
```
File | Line | Function
-- | -- | --
[PHP] |   | errorHandler->error
C:\My.Files\My.Projects\Web.Hosts\mybb.test\mybbdev\inc\functions_search.php | 286 | preg_replace
C:\My.Files\My.Projects\Web.Hosts\mybb.test\mybbdev\inc\functions_search.php | 1406 | clean_keywords_ft
C:\My.Files\My.Projects\Web.Hosts\mybb.test\mybbdev\search.php | 1606 | perform_search_mysql_ft
```

Don't know if it's related.

Part of the `threads` table schema:
```
	PRIMARY KEY (`tid`),
	INDEX `fid` (`fid`, `visible`, `sticky`),
	INDEX `dateline` (`dateline`),
	INDEX `lastpost` (`lastpost`, `fid`),
	INDEX `firstpost` (`firstpost`),
	INDEX `uid` (`uid`),
	FULLTEXT INDEX `subject` (`subject`)
)
COLLATE='utf8mb4_general_ci'
ENGINE=MyISAM
```

Is there any other information I should append?

BTW, applying #3942 doesn't solve search problem, it still return all the records.

**Comment by euantorano** [comment] 2020-04-18 06:31
That’s interesting with the warning, I wasn’t getting that. As it’s talking about numbers out of order, I’m guessing the minimum word length is being worked out to be less than or equal to 1 - I can’t think of another reason. What’s your minsearchword setting set to in the ACP?

I believe the original report was that it returned no records, so it returning all records is possibly a step forward 😂

I’ll have another look today.

**Comment by yuliu** [comment] 2020-04-18 06:36
> I’m guessing the minimum word length is being worked out to be less than or equal to 1 - I can’t think of another reason. What’s your minsearchword setting set to in the ACP?

Yeah good guess! The min search word length is 1.

I'll try to get a descriptive report for innodb and mysiam.

**Comment by euantorano** [comment] 2020-04-18 06:38
Yeah, we seem to subtract 1, so the limit will be `{1,0}` which will cause it. I’ll play with that setting and add some logic to handle that case today.

**Comment by yuliu** [comment] 2020-04-18 07:03
OK, more descriptive report. First is an InnoDB database on a production forum:
- MyBB 1.8.22 official build, no mods, no plugins affecting search.
- MyBB search settings:
  - Minimum Search Word Length: `2`
  - Hard Limit for Maximum Search Results : `0`
- Ubuntu / PHP: 7.2.24 / MySQLi: 5.7.29 / Engine: InnoDB / Collation: utf8mb4_general_ci
- MySQL variables:
  - `ft_boolean_syntax`: `+ -><()~*:""&|`
  - ` innodb_ft_min_token_size`: `3`
- SHOW CREATE TALBE `threads`:
```
CREATE TABLE `community_mybb_threads` (
 `tid` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `fid` smallint(5) unsigned NOT NULL DEFAULT '0',
 `subject` varchar(120) NOT NULL DEFAULT '',
 `prefix` smallint(5) unsigned NOT NULL DEFAULT '0',
 `icon` smallint(5) unsigned NOT NULL DEFAULT '0',
 `poll` int(10) unsigned NOT NULL DEFAULT '0',
 `uid` int(10) unsigned NOT NULL DEFAULT '0',
 `username` varchar(80) NOT NULL DEFAULT '',
 `dateline` int(10) unsigned NOT NULL DEFAULT '0',
 `firstpost` int(10) unsigned NOT NULL DEFAULT '0',
 `lastpost` int(10) unsigned NOT NULL DEFAULT '0',
 `lastposter` varchar(120) NOT NULL DEFAULT '',
 `lastposteruid` int(10) unsigned NOT NULL DEFAULT '0',
 `views` int(100) unsigned NOT NULL DEFAULT '0',
 `replies` int(100) unsigned NOT NULL DEFAULT '0',
 `closed` varchar(30) NOT NULL DEFAULT '',
 `sticky` tinyint(1) NOT NULL DEFAULT '0',
 `numratings` smallint(5) unsigned NOT NULL DEFAULT '0',
 `totalratings` smallint(5) unsigned NOT NULL DEFAULT '0',
 `notes` text NOT NULL,
 `visible` tinyint(1) NOT NULL DEFAULT '0',
 `unapprovedposts` int(10) unsigned NOT NULL DEFAULT '0',
 `deletedposts` int(10) unsigned NOT NULL DEFAULT '0',
 `attachmentcount` int(10) unsigned NOT NULL DEFAULT '0',
 `deletetime` int(10) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (`tid`),
 KEY `fid` (`fid`,`visible`,`sticky`),
 KEY `dateline` (`dateline`),
 KEY `lastpost` (`lastpost`,`fid`),
 KEY `firstpost` (`firstpost`),
 KEY `uid` (`uid`),
 FULLTEXT KEY `subject` (`subject`)
) ENGINE=InnoDB AUTO_INCREMENT=18803 DEFAULT CHARSET=utf8mb4
```
- SHOW CREATE TALBE `posts`:
```
CREATE TABLE `community_mybb_posts` (
 `pid` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `tid` int(10) unsigned NOT NULL DEFAULT '0',
 `replyto` int(10) unsigned NOT NULL DEFAULT '0',
 `fid` smallint(5) unsigned NOT NULL DEFAULT '0',
 `subject` varchar(120) NOT NULL DEFAULT '',
 `icon` smallint(5) unsigned NOT NULL DEFAULT '0',
 `uid` int(10) unsigned NOT NULL DEFAULT '0',
 `username` varchar(80) NOT NULL DEFAULT '',
 `dateline` int(10) unsigned NOT NULL DEFAULT '0',
 `message` text NOT NULL,
 `ipaddress` varbinary(16) NOT NULL DEFAULT '',
 `includesig` tinyint(1) NOT NULL DEFAULT '0',
 `smilieoff` tinyint(1) NOT NULL DEFAULT '0',
 `edituid` int(10) unsigned NOT NULL DEFAULT '0',
 `edittime` int(10) unsigned NOT NULL DEFAULT '0',
 `editreason` varchar(150) NOT NULL DEFAULT '',
 `visible` tinyint(1) NOT NULL DEFAULT '0',
 PRIMARY KEY (`pid`),
 KEY `tid` (`tid`,`uid`),
 KEY `uid` (`uid`),
 KEY `visible` (`visible`),
 KEY `dateline` (`dateline`),
 KEY `ipaddress` (`ipaddress`),
 KEY `tiddate` (`tid`,`dateline`),
 FULLTEXT KEY `message` (`message`)
) ENGINE=InnoDB AUTO_INCREMENT=367927 DEFAULT CHARSET=utf8mb4
```

Test result for keywords `adobe` (no false positive result found):
- Standard search for threads-only returns 2 records;
- Standard search for threads & posts returns 16 records;
- Fulltext search for threads-only returns 1 records;
- Fulltext search for threads & posts returns 9 records.

Test result for keywords `运行记录` (in Chinese, no false positive result found):
- Standard search for threads-only returns 2 records;
- Standard search for threads & posts returns 3 records;
- Fulltext search for threads-only returns _none_;
- Fulltext search for threads & posts returns _none_;

Applying #3942 doesn't change the above result.

**Comment by yuliu** [comment] 2020-04-18 07:37
Second is a MyISAM database on a test forum (threads & posts differ from the 1st one):
- MyBB 1.8.22 official build, no mods, no plugins affecting search.
- MyBB search settings:
  - Minimum Search Word Length: `2`
  - Hard Limit for Maximum Search Results : `0`
- Windows / PHP: 7.4.4 / MySQLi: 5.7.29 / Engine: MyISAM / Collation: utf8mb4_general_ci
- MySQL variables:
  - `ft_boolean_syntax`: `+ -><()~*:""&|`
  - `ft_min_word_len`: `4`
  - `ft_stopword_file`:  (built-in)
- SHOW CREATE TALBE `threads`:
```
CREATE TABLE `mybb_threads` (
	`tid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`fid` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`subject` VARCHAR(120) NOT NULL DEFAULT '',
	`prefix` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`icon` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`poll` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`uid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`username` VARCHAR(80) NOT NULL DEFAULT '',
	`dateline` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`firstpost` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`lastpost` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`lastposter` VARCHAR(120) NOT NULL DEFAULT '',
	`lastposteruid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`views` INT(100) UNSIGNED NOT NULL DEFAULT '0',
	`replies` INT(100) UNSIGNED NOT NULL DEFAULT '0',
	`closed` VARCHAR(30) NOT NULL DEFAULT '',
	`sticky` TINYINT(1) NOT NULL DEFAULT '0',
	`numratings` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`totalratings` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`notes` TEXT NOT NULL,
	`visible` TINYINT(1) NOT NULL DEFAULT '0',
	`unapprovedposts` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`deletedposts` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`attachmentcount` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`deletetime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`tid`),
	INDEX `fid` (`fid`, `visible`, `sticky`),
	INDEX `dateline` (`dateline`),
	INDEX `lastpost` (`lastpost`, `fid`),
	INDEX `firstpost` (`firstpost`),
	INDEX `uid` (`uid`),
	FULLTEXT INDEX `subject` (`subject`)
) COLLATE='utf8mb4_general_ci' ENGINE=MyISAM AUTO_INCREMENT=276328
```
- SHOW CREATE TALBE `posts`:
```
CREATE TABLE `mybb_posts` (
	`pid` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`tid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`replyto` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`fid` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`subject` VARCHAR(120) NOT NULL DEFAULT '',
	`icon` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
	`uid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`username` VARCHAR(80) NOT NULL DEFAULT '',
	`dateline` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`message` TEXT NOT NULL,
	`ipaddress` VARBINARY(16) NOT NULL DEFAULT '',
	`includesig` TINYINT(1) NOT NULL DEFAULT '0',
	`smilieoff` TINYINT(1) NOT NULL DEFAULT '0',
	`edituid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`edittime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`editreason` VARCHAR(150) NOT NULL DEFAULT '',
	`visible` TINYINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`pid`),
	INDEX `tid` (`tid`, `uid`),
	INDEX `uid` (`uid`),
	INDEX `visible` (`visible`),
	INDEX `dateline` (`dateline`),
	INDEX `ipaddress` (`ipaddress`),
	INDEX `tiddate` (`tid`, `dateline`),
	FULLTEXT INDEX `message` (`message`)
) COLLATE='utf8mb4_general_ci' ENGINE=MyISAM AUTO_INCREMENT=3806572
```

Test result for keywords `adobe` (no false positive result found):
- Standard search for threads-only returns 4 records;
- Standard search for threads & posts returns 32 records;
- Fulltext search for threads-only returns 2 records;
- Fulltext search for threads & posts returns 18 records.

Test result for keywords `运行记录` (in Chinese, no false positive result found):
- Standard search for threads-only returns 3 records;
- Standard search for threads & posts returns 5 records;
- Fulltext search for threads-only returns _none_;
- Fulltext search for threads & posts returns _none_;

Applying #3942 doesn't change the above results.

**Comment by euantorano** [comment] 2020-04-18 07:39
I would expect different result counts between standard and full text, but 0 results is odd. Can you try running the above SQL query with the search terms too?

**Comment by yuliu** [comment] 2020-04-18 07:49
> I would expect different result counts between standard and full text, but 0 results is odd. Can you try running the above SQL query with the search terms too?

The query specified in https://github.com/mybb/mybb/issues/3937#issuecomment-615483524 ?

In the 1st InnoDB database:
`SELECT * FROM mybb_threads WHERE match(subject) against ('adobe' IN BOOLEAN MODE);`
returns 1 record.
`SELECT * FROM mybb_threads WHERE match(subject) against ('运行记录' IN BOOLEAN MODE);`
returns _none_.

In the 2rd MyISAM database:
`SELECT * FROM mybb_threads WHERE match(subject) against ('adobe' IN BOOLEAN MODE);`
returns 2 records.
`SELECT * FROM mybb_threads WHERE match(subject) against ('运行记录' IN BOOLEAN MODE);`
returns _none_.

**Comment by euantorano** [comment] 2020-04-18 08:47
Yeah, that's exactly what I meant. So it looks like the MYSQL FULLTEXT search is returning no results at all, which would explain why MyBB doesn't return any either. Perhaps this is another MySQL limitation...

**Comment by euantorano** [comment] 2020-04-18 09:06
Ok, the error about `Compilation failed: numbers out of order in {} quantifier at offset 8` should be fixed now with fdaffdc.

**Comment by euantorano** [comment] 2020-04-18 09:11
I just tested searching for `运行记录` with a thread with the subject `运行记录 test` and it gave me a result:

<img width="693" alt="Screenshot 2020-04-18 at 10 07 42" src="https://user-images.githubusercontent.com/748913/79633303-75b51f00-815c-11ea-9e51-ef36c264dca0.png">

Details:

- macOS / PHP: 7.4.4 / Engine: MyISAM / Collation: utf8mb4_general_ci
- `ft_boolean_syntax = + -><()~*:""&|`
- `ft_min_word_len = 4`
- `version = 10.4.11-MariaDB-1:10.4.11+maria~bionic`
- `Minimum Search Word Length = 2`
- `Hard Limit for Maximum Search Results = 0`
- MyBB `feature` branch with #3942 applied

**Comment by yuliu** [comment] 2020-04-18 10:02
Don't know why.

Still in the 2rd MyISAM database, I've posted another thread that has the keywords and... it can be found out with or without applying #3942.
After that, I've tried running `REPAIR TABLE threads;` and removing & adding back the fulltext index, but is doesn't make any different.

**Comment by euantorano** [comment] 2020-04-18 11:26
That is extremely odd indeed. Is this running locally and is there any chance you can try it after converting to InnoDB (sorry, can’t remember if you’ve tried already and I’m away from the computer at the moment)?

**Comment by yuliu** [comment] 2020-04-18 13:32
OK, tried following:
- converted `threads` to use InnoDB and `innodb_ft_min_token_size=3`;
- still on MyISAM, change `ft_min_word_len=1` and repair table `threads`.
Query `SELECT * FROM mybb_threads WHERE match(subject) AGAINST ('运行记录' IN BOOLEAN MODE);`  in both condition returns the same result, the new titled thread can be found, the former existing threads can't be found.

I made several new threads with following titles and tried the same query. Following threads can be found by the SQL query:
- `运行记录？？？`
- `Ttitle 运行记录 End`  _(mind the space)_
- `发表主题 运行记录` _(mind the space)_

Following threads can't be found by the SQL query:
- `发表主题运行记录`
- `Ttitle运行记录End`

It should be a separated issue about CJK from the one reported in the original thread. CJKs usually don't have delimiters like space ` `  and for CJKs MySQL has its support but not for utf8 charset encoding: https://dev.mysql.com/worklog/task/?id=6607 .
I'm sorry to mess it up here. Should I continue to discuss the CJK problem in this issue?

Furthermore, I tried several threads having `tydzień` in title, the threads can be returned by the SQL query and MyBB without #3942 applied, on my test forum, with both MyISAM and InnoDB. But on the community forum, the search returns nothing. Don't know why.

**Comment by euantorano** [comment] 2020-04-18 17:23
Yeah, probably best to create a new issue for the CJKs, though I ave no idea what to do to fix it.

When I tested this issue locally on a brand new install with default settings, using a thread the same as [this one](https://community.mybb.com/thread-227334.html), no results were returned until I applied #3942 at all. It seems MySQL's full text search has a few quirks.

**Comment by yuliu** [comment] 2020-04-18 17:42
> Yeah, probably best to create a new issue for the CJKs, though I have no idea what to do to fix it.

OK, I'll later take some time to see if the Chinese-based forum software Discuz! has some tricks for CJK fulltext search.

> When I tested this issue locally on a brand new install with default settings, using a thread the same as [this one](https://community.mybb.com/thread-227334.html), no results were returned until I applied #3942 at all. It seems MySQL's full text search has a few quirks.

Seems so. I tried the same title on a new install with default settings using the same environment as the MyISAM database one, it just returned the expected result. The MySQL 5.7.29 x64 environment on Windows uses default configurations (`my.ini` only contains `basedir` & `datadir` settings).

**Comment by Sama34** [comment] 2020-04-19 01:20
I did test in my local environment and searching for `tydzień` returns no results whereas `运行记录` seems to work just fine with a 1.8.22 install.

I seem to get the same error with `Minimum Search Word Length` set to `1`.
```
Warning [2] preg_replace(): Compilation failed: numbers out of order in {} quantifier at offset 8 - Line: 286 - File: inc/functions_search.php PHP 7.2.24-0ubuntu0.18.04.3 (Linux)
```

You code seems to fix these and returns result for both `tydzień` and `运行记录`.

**Comment by Ben-MyBB** [comment] 2020-04-22 20:40
Could this be related to https://github.com/mybb/mybb/issues/2056 ?

**Comment by euantorano** [comment] 2020-04-22 20:43
I don’t believe so, but does seem an easy fix.

**Comment by Eldenroot** [comment] 2020-04-23 18:39
@euantorano please can we try to fix #2056 along side with this one? I think it is not solved for me with this fix.

**Comment by euantorano** [comment] 2020-04-23 18:41
I'm not entirely clear on #2056 right now, I need to look at it further and it will be a separate PR.

**Comment by Eldenroot** [comment] 2020-04-25 12:07
I tested only with English language pack and few threads (test board), Works fine (InnoDB). So I would like to merge this into next release and maybe then we will get more reports and this will need small adjustments... others?

**Closed** 2020-04-25 12:10 UTC
Labels: b:1.8, s:review-needed, t:bug
