### ISSUE TITLE
Broken link - http://docs.mybb.com/SEF_URLs.html

### ISSUE THREAD

**Issue by GrannyLVP** [mybb/mybb#2308] opened 2016-01-10 09:28 UTC
Admin CP --> Configuration --> Server and Optimization Options

"Search engine friendly URLs change the MyBB links to shorter URLs which search engines prefer and are easier to type. showthread.php?tid=1 becomes thread-1.html. Once this setting is enabled you need to make sure you have the MyBB .htaccess in your MyBB root directory (or the equivalent for your web server). Automatic detection may not work on all servers. Please see the MyBB Docs for assistance."

The link to the MyBB Docs is http://docs.mybb.com/SEF_URLs.html and this link brings up a 404.

**Comment by JoshHarmon** [comment] 2016-01-11 00:45
Yikes! That's not good. I'll fix it on the documentation site for now and we can fix it in the ACP afterwards.

**Comment by Destroy666x** [comment] 2016-01-12 07:27
This is a duplicate of 2 issues - https://github.com/mybb/mybb/issues/1729 and an issue in the docs repository mentioned there.

**Closed** 2016-01-12 07:27 UTC
Labels: s:duplicate
