### ISSUE TITLE
[color] tags with rgba() colour spec are unrendered

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4231] opened 2021-01-11 07:44 UTC
e.g., [color=rgba(224, 224, 224, 0.8)]The color tag surrounding this text will not render[/color].

This bug was reported on Discord.

I'm not sure how the rgba() colour specification got there in the first place; presumably it was due to a copy-n-paste operation of rich text.

Neither the editor (as part of its colour normalisation) nor the MyBB parser currently handle rgba() colour specifications.

Original thread: [[color] tags with rgba() colour spec are unrendered](https://community.mybb.com/thread-230808.html)

**Comment by Eldenroot** [comment] 2021-01-11 09:53
There are about 10+ issues related to sceditor, I dont know your internal plans for MyBB 1.9, but maybe we should consider to replace sceditor in 1.9 and maybe some blog post about mybb 1.9 dev progress would be nice. Also consider if somebody can fix these bugs for MyBB 1.8... This is the major issue and many people have problem with this when using MyBB, because editor is the first thing which is used daily. It means less users, bad reviews for MyBB project etc.

**Comment by euantorano** [comment] 2021-01-11 11:17
The plan for 1.9 has always been to replace SCEditor. There is a thread on the forums regarding it. It's still not 100% chosen exactly what to replace it with.

For 1.8, the plan is to fix as many of the bugs as we possibly can with SCEditor - hence why we forked it to the mybb organisation.

In this case, the problem isn't with SCEditor but with the core post parser which is MyBB specific code.

**Comment by lairdshaw** [comment] 2021-01-12 04:41
I don't think this is an especially difficult bug to fix - we can just add support for 8-digit hex RGBA specs to the parser, and support in `jscripts/bbcodes_sceditor.js` for converting `rgba()` to 8-digit hex. I think for the Javascript though that it's best to build on the `_normaliseColour(colorStr)` function copied into that .js file from the core SCEditor in PR #4186, so I won't submit a fix for this issue until (if) that PR is merged.

**Comment by Eldenroot** [comment] 2021-01-12 17:28
Need to speed up merging and testing, thats all...

**Comment by euantorano** [comment] 2021-01-12 17:37
> Need to speed up merging and testing, thats all...

I'm going as fast as I can, sorry!

**Comment by Eldenroot** [comment] 2021-01-12 17:42
Euan it is not against you! MyBB dev team has a lot of talented users who can test and provide feedback... There are many ways how to improve it, check Flarum trainee for example, they had same issue with small activy in the dev team and now they have a lot of new devs...

**Comment by Sama34** [comment] 2021-01-13 06:42
I think adding support for `rgba()` is reasonable.

**Comment by dvz** [comment] 2021-01-13 12:27
IMO we should keep MyCode parsing as simple as possible - it will have to be supported for a long time.

Transparency seems unnecessary for most boards (custom colors already cause readability and spam issues when overused).

**Comment by lairdshaw** [comment] 2021-01-13 18:42
Agreed that MyCode parsing should be kept as simple as possible, and that transparency is unnecessary. We would not be adding support because we wanted to offer extended parsing, but because it is unavoidable: sometimes, presumably during copy-n-paste, the browser and editor conspire to generate an rgba() color specification, and if we don't handle this situation, the associated `color` tag doesn't render, messing up the parser's output.

**Comment by dvz** [comment] 2021-01-13 18:47
If you mean handling this client-side only (convert to hex and remove transparency) - that sounds good.

**Comment by Sama34** [comment] 2021-01-13 20:02
Also, unsure if already checked, but I think administrators should be able to create their own MyCodes that overwrites core ones, in this case the color one.

Which would make it unnecessary for us to add it in core.

**Comment by lairdshaw** [comment] 2021-01-13 22:39
@dvz @Sama34 Happy to restrict rgba() support to the client, which my PR does.

**Closed as completed** 2021-02-07 15:34 UTC
Labels: t:bug, b:1.8, s:resolved
