### ISSUE TITLE
Select2 4.0

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb#2182] opened 2015-08-26 09:10 UTC
We're using Select2 3.5.3 which is the latest for 3.x, however 4.0 has already been released too so we should look whether we can upgrade.

**Comment by JoshHarmon** [comment] 2015-08-26 18:58
What new functionality does 4.0 provide (asking here in case others are curious)?

**Comment by JN-Jones** [comment] 2015-08-26 20:16
Haven't checked the exact change log but I'd say the main reasons to update are the bug fixes ;) Don't know whether and how long they plan to support 3.x

**Comment by Cu8eR** [comment] 2016-01-29 16:24
For 1.8.7 we can update to the latest version Select2 v3.5.2 - last release in 3.x branch. Or we can jump directly to v4, but I think it needs more testing

**Comment by Eric-Jackson** [comment] 2016-05-14 13:44
It is a full rewrite, some of the changes from 3.x -> 4.x are here: https://select2.github.io/announcements-4.0.html

> Less specific selectors allowing for Select2 to be styled to fit the rest of your application.

This catches my attention personally. Not worth it in itself but a positive for upgrading.

**Comment by JN-Jones** [comment] 2016-11-21 08:11
We should try to update all 3rd party libraries in one of the next releases. As this requires some testing I'd postpone this to 1.8.10 however we should try to get this done as one of the first things so maybe someone should already start with this @mybb/developers

**Comment by Shade-** [comment] 2017-07-24 12:15
Apparently, Select2 4.0 has an issue with inputs not firing AJAX requests (https://github.com/select2/select2/issues/3294). MyBB uses inputs to gather usernames using Select2. I would wait till the issue is solved from Select2's authors.

**Comment by Cu8eeeR** [comment] 2017-07-24 14:41
@Shade- it seems to be an old unfixed issue, I hope it will be fixed sooner than later. I agree with your suggestion, would be better to merge update for all others 3rd libraries and leave Select2 library v3.5.3 until it gets fixed.

**Comment by Ben-MyBB** [comment] 2020-06-30 09:31
Thoughts on this one? I think we should just close this IMHO, we haven't got any issues related to the current Select2 version and given the 1.8 series is due to be dropped a year after 1.9 is released should we still be looking to update?

@justinsoltesz / @euantorano ?

**Comment by euantorano** [comment] 2020-06-30 09:46
It looks like [Select2 are currently working on v4.1.0](https://github.com/select2/select2/tags). Upgrading to 4.0.0 would mean we'd still be behind once that version is released.

The [changelog](https://github.com/select2/select2/blob/develop/CHANGELOG.md) is also worth a look, specifically:

> Removed legacy support for `<input />` tags

This may affect us, based on past comments.

I think we're best staying on the current version unless there's any serious issues with it.

**Comment by effone** [comment] 2020-06-30 13:34
I am strongly against updating select2. I had some homework on it and it appeared like not just dump the latest library in our jscript folder and we are good to go. It needs some amount of work to fit in like it was. Another support to my statement can be we merely depend on  / use the all awesomeness of select2, we just use it as our autocomplete plugin (don't know why we chose that heavy plugin just to use a single feature of it).

My suggestion is let it be as is and ditch it when we jump to 1.9

**Comment by Ben-MyBB** [comment] 2020-06-30 13:36
@JordanMussi @yuliu @Sama34 any objections to closing this?

**Comment by JordanMussi** [comment] 2020-06-30 19:25
What's 1.9 going to be using? Either defer to 1.9 or close. I am strongly against a change like this with huge potential for breakage...

**Comment by euantorano** [comment] 2020-06-30 19:41
Not sure for 1.9, we were considering writing something lighter weight. I’d prefer closing for now.

**Comment by Sama34** [comment] 2020-07-09 08:03
I think we could keep this open to track it for 1.9 but personally I'd vouch to drop it entirely or expand its usage. It is a big library for which we use in like 3 places (serious joke).

What about @justinsoltesz , do you think we might drop this plugin?

**Comment by effone** [comment] 2020-07-09 09:10
>Not sure for 1.9, we were considering writing something lighter weight. I’d prefer closing for now.

I was already working on it. Needs a very little effort to fit in MyBB.
https://github.com/effone/jquery.fyl

**Comment by euantorano** [comment] 2020-07-20 10:39
I'd vote for closing this and opening a new issue for replacing Select2 completely.

**Closed** 2021-03-27 21:32 UTC
Labels: 3rdparty, b:1.8, p:medium, s:confirmed
