### ISSUE TITLE
$errors array needs explicit declaration in member.php

### ISSUE THREAD

**Issue by Devilshakerz** [mybb/mybb#2765] opened 2017-06-07 11:29 UTC
Since PHP 7.1, arrays need explicitly declaring; you can no longer implicitly cast an empty string to an empty array.

Quote:As of PHP 7.1.0, applying the empty index operator on a string throws a fatal error. Formerly, the string was silently converted to an array.
(http://php.net/manual/en/language.types.array.php)

In member.php, line 255 causes an error if the Captcha test fails. It assumes &#36;errors is already an array.

We need to replace (line 205)

PHP Code:&#36;errors&nbsp;=&nbsp;"";&nbsp;
with

PHP Code:&#36;errors&nbsp;=&nbsp;array();&nbsp;

Original thread: [$errors array needs explicit declaration in member.php](https://community.mybb.com/thread-210918.html)

**Comment by James-Oakley** [comment] 2017-06-21 19:36
Where do you want comments on issues - here, or in the discussion thread attached to the commit / PR?

There's an additional change needed, that I found on my site when I fixed this manually. If we just change the declaration to be array(), no user can register, because they always get told to fix the following errors (with no errors listed).

The test to see whether the user has registered without error comes in line 307. Currently, we check is_array($errors), which relies on the fact the variable was originally declared as a string. We need to change that to empty($errors)

**Comment by James-Oakley** [comment] 2017-06-21 19:55
Sorry - it's not as simple as ^ either. I'll keep looking and try and track down all the related required changes

**Comment by JordanMussi** [comment] 2017-07-05 16:44
@James-Oakley once the issue is confirmed and has been pushed to GitHub posting comments here is best as they might be missed on the forums.

Fixed in #2786

**Closed** 2017-09-05 13:08 UTC
Labels: 1.8, bug, s:fixed
