### ISSUE TITLE
404 cron documentation not found

### ISSUE THREAD

**Issue by ATofighi** [mybb/mybb#2087] opened 2015-06-27 06:14 UTC
I try to schedule a weekly backup.
via [tools &amp; maintenance] [task manager]  I select [weekly backup]
when I click [save and finish] I get a screen:

"The selected task has been updated successfully.

WARNING: You are about to enable a task that is only meant to be run via cron (Please see the MyBB Docs for more information). Continue?"

when I click on the link -MyBB Docs- , I get a 404 error.

I use 1.8.5

Original thread: [404 cron documentation not found](http://community.mybb.com/thread-172405.html)

**Comment by Destroy666x** [comment] 2015-06-27 11:04
This is a duplicate of https://github.com/mybb/mybb/issues/1729 - there are many more broken links.

**Closed** 2015-06-27 11:05 UTC
Labels: s:duplicate
