### ISSUE TITLE
Permissions not set for newly created subforums 

### ISSUE THREAD

**Issue by GasmoN** [mybb/mybb#4162] opened 2020-10-09 18:01 UTC
If you got ACP > *Select any of your forums* > "Add child forum" and remove "View" permission for all usergroups except "Administartors" usergroup, and then click on "Save Forum". That forum will create without proglems, but users that are not in "Administrators" group and guests will be able to see that subforum. In order to fix this you need to go and and click "Edit Subforum" and do nothing, just click again "Save Forum".

Notice: When you go to edit subforum, the permissions will be like you set when you was creating the forum, so you just need to click "Save Forum" in order to fix this problem.

PS: I am using currently latest version of mybb - 1.8.24 (1824)

**Comment by Stefan-MyBB** [comment] 2020-10-09 18:46
Duplicate of #4151?

**Comment by GasmoN** [comment] 2020-10-09 20:41
Could be, I didn't saw that that issue is opened.

**Closed as completed** 2020-10-11 14:14 UTC
Labels: s:duplicate
