### ISSUE TITLE
Delete a user ACP

### ISSUE THREAD

**Issue by PaulBender** [mybb/mybb#2153] opened 2015-07-12 16:35 UTC
- A user's uid number to config.php Add to super_admins into line.
- AdminCP deleted from the member that you add this and you will get the following error.

Original thread: [Delete a user ACP](http://community.mybb.com/thread-173079.html)

**Comment by Destroy666x** [comment] 2015-07-12 18:13
Duplicate of https://github.com/mybb/mybb/issues/1981

**Closed** 2015-07-12 18:14 UTC
Labels: s:duplicate
