### ISSUE TITLE
"Put the editor in source mode by default" ineffective when previewing

### ISSUE THREAD

**Issue by Stefan-ST** [mybb/mybb#1875] opened 2015-02-20 19:05 UTC
The option "Put the editor in source mode by default" has no effect when you preview a post/thread.

**Comment by Destroy666x** [comment] 2015-02-20 19:24
Are you sure it's a core bug? Can't reproduce on my local forum: https://docs.google.com/file/d/0B6pgReiHWGdSbGd6M24zbWhTTjA/edit?usp=drivesdk

**Comment by Stefan-ST** [comment] 2015-02-20 21:12
@Destroy666x I can't reproduce it on a test forum either. Perhaps a browser cache issues on upgraded boards?

**Comment by Destroy666x** [comment] 2015-02-20 21:54
I don't think so. My testing forum is a MySQL upgrade from 1.6.16 to 1.8.4. I guess it applies only to the community forum and it also happens randomly there - I previewed one post 10 times and 3 times it was incorrectly WYSIWYG, 7 correct source mode. On the testing forum all 10 tries with the same post were in source mode. I have no idea what may be wrong,

**Comment by Destroy666x** [comment] 2015-02-20 22:11
Just noticed an error with `undo.js` when it happened during full edit, most likely culprit of this issue:

> Uncaught TypeError: Cannot read property 'length' of undefined undo.js:2

**Comment by Sama34** [comment] 2015-02-21 04:33
@brunoais

**Comment by Stefan-ST** [comment] 2015-02-21 11:30
@Destroy666x Good catch, that's probably the reason. :+1: The plugins seams to have problems with some MyCode.

**Comment by brunoais** [comment] 2015-02-21 13:03
> Uncaught TypeError: Cannot read property 'length' of undefined undo.js:2

On line 2, there's this:
`'use strict';`

@Destroy666x What is on your line 2?

**Comment by JN-Jones** [comment] 2015-02-21 13:11
We're using a compressed version so everything is in line 2: https://github.com/mybb/mybb/blob/feature/jscripts/sceditor/editor_plugins/undo.js

**Comment by Stefan-ST** [comment] 2015-02-21 13:34
@brunoais Actually there is a problem with strA in line 51.
```js
		var simpleDiff = function (strA, strB) {
			var start, end, aLenDiff, bLenDiff,
				aLength = strA.length,
				bLength = strB.length,
				length  = Math.max(aLength, bLength);
```

**Comment by brunoais** [comment] 2015-02-21 17:19
> @brunoais There is a problem with strA in line 51.

What is the problem?

**Comment by Stefan-ST** [comment] 2015-02-21 17:57
```
Uncaught exception: TypeError: Cannot convert 'strA' to object
Error thrown at line 50, column 3 in <anonymous function: $.sceditor.plugins.undo>(strA, strB) in http://localhost/mybb/jscripts/sceditor/editor_plugins/undo.js?ver=1804:
    var start, end, aLenDiff, bLenDiff,
called from line 164, column 3 in <anonymous function: base.signalValuechangedEvent>(e) in http://localhost/mybb/jscripts/sceditor/editor_plugins/undo.js?ver=1804:
    charChangedCount += simpleDiff(previousValue, rawEditorValue);
called via Function.prototype.apply() from line 3, column 29179 in <anonymous function: a.sceditor.PluginManager>(a, b) in http://localhost/mybb/jscripts/sceditor/jquery.sceditor.bbcode.min.js:
    d[c][g].apply(e,a)
called from line 3, column 29363 in <anonymous function: c.call>() in http://localhost/mybb/jscripts/sceditor/jquery.sceditor.bbcode.min.js:
    g(arguments,!1)
called from line 2, column 40431 in <anonymous function: V>(b) in http://localhost/mybb/jscripts/sceditor/jquery.sceditor.bbcode.min.js:
    t.call(d.type+"Event",b,lb),delete d.type,c=a.Event((b.target===n?"scesrc":"scewys")+b.type,d),g.trigger(c,lb),c.isDefaultPrevented()&&b.preventDefault(),c.isImmediatePropagationStopped()&&c.stopImmediatePropagation(),c.isPropagationStopped()&&c.stopPropagation()
called via Function.prototype.apply() from line 3, column 16426 in <anonymous function: dispatch>(a) in http://localhost/mybb/jscripts/jquery.js?ver=1804:
    (!a.namespace_re||a.namespace_re.test(e.namespace))&&(a.handleObj=e,a.data=e.data,c=((m.event.special[e.origType]||{}).handle||e.handler).apply(f.elem,i),void 0!==c&&(a.result=c)===!1&&(a.preventDefault(),a.stopPropagation()))
called via Function.prototype.apply() from line 3, column 10340 in <anonymous function: r.handle>(a) in http://localhost/mybb/jscripts/jquery.js?ver=1804:
    return typeof m===K||a&&m.event.triggered===a.type?void 0:m.event.dispatch.apply(k.elem,arguments)
called via Function.prototype.apply() from line 3, column 14276 in <anonymous function: trigger>(b, c, d, e) in http://localhost/mybb/jscripts/jquery.js?ver=1804:
    b.type=n>1?i:k.bindType||p,f=(m._data(h,"events")||{})[b.type]&&m._data(h,"handle"),f&&f.apply(h,c),f=g&&h[g],f&&f.apply&&m.acceptData(h)&&(b.result=f.apply(h,c),b.result===!1&&b.preventDefault());
called from line 3, column 31005 in <anonymous function: trigger>() in http://localhost/mybb/jscripts/jquery.js?ver=1804:
    m.event.trigger(a,b,this)
called via Function.prototype.call() from unknown location in <anonymous function: each>(a, b, c) in http://localhost/mybb/jscripts/jquery.js?ver=1804:
```
@brunoais Does that help you?

**Comment by brunoais** [comment] 2015-02-21 20:33
Only to remove some possible causes. It didn't help me to find that specific cause.
When I test on my end, all goes normally.
I can't find any problems with it. Please get me a list of reproduction steps and requirements.

**Comment by Destroy666x** [comment] 2015-02-23 22:46
@brunoais, are there any required changes in SCE 1.4.6 for the undo plugin to work besides including the `undo.js` file itself?

**Comment by brunoais** [comment] 2015-02-24 08:24
None, as much as I know.

**Comment by brunoais** [comment] 2015-02-24 08:39
I didn't test it, so I don't know.

Can you get me a function call history instead of just the stacktrace. I need to know who calls whom and with which contents. With that, I can pinpoint what failed in the puzzle.

**Comment by Stefan-ST** [comment] 2015-02-24 16:15
@brunoais I'm not used to debugging javascript code. Is there any easy way (e.g. browser plugin) to generate the information you need?

**Comment by brunoais** [comment] 2015-02-24 16:33
I don't know.

**Comment by Destroy666x** [comment] 2015-03-04 10:56
As I see SCEditor 1.4.6 got released, so we should update to it and try.

**Comment by novalis111** [comment] 2015-03-06 11:36
It doesn't... the problem persists in IE, works in Gecko + Webkit though. Quick fix for me was just inserting 
    if (!a){a = {}};
in place, but the problem is somewhere else. The error is thrown in undo.js, you can see it if you start the developer tools in IE (sigh). It is preventing the following JS code from execution, which is why the options (eg sourceMode) won't get applied. I can't trace it down further, sorry.

**Comment by samclarke** [comment] 2015-03-06 22:34
From the look of the stacktrace I think this is caused by the undo plugin trying to do a diff on the previous value before a previous value is set.

I'm struggling to reproduce this though so I can't test if this is the issue or not. I've added a [fix for what I think the issue is](https://raw.githubusercontent.com/samclarke/SCEditor/master/src/plugins/undo.js). Could you see if that solves the problem for you?

**Comment by martec** [comment] 2015-03-07 02:06
@samclarke 
yes... your fix work...
but 1.4.6 has bug for me...

http://i.imgur.com/0aZeKge.png

no possible more click in several buttons like bold, align etc... in source mode. Can reproduce in http://www.sceditor.com/
So mybb team not upgreade to 1.4.6 for now.

**Comment by brunoais** [comment] 2015-03-07 09:36
Note: samclarke/SCEditor#395 is duplicate of: samclarke/SCEditor#394
The fix is underway.

**Comment by Destroy666x** [comment] 2015-03-07 13:18
@samclarke, thanks, the fix seems to work. Do you plan to release 1.4.7 in the near future?

**Comment by Sama34** [comment] 2015-03-07 19:48
If the problem is only present in the plugin file we can probably just update that in next MyBB version.

**Comment by martec** [comment] 2015-03-08 01:17
@Sama34 
yes... replace only undo plugin is better solution for now.

**Comment by Destroy666x** [comment] 2015-03-08 10:59
For fixing this issue yes, but we should update to SCE 1.4.6 nonetheless and it has another major bug with source mode as I can see, thus my question to see if it's worth updating it in 1.8.5.

**Comment by samclarke** [comment] 2015-03-08 19:27
I'm testing 1.4.7 at the moment so it should be released soon.

**Comment by Destroy666x** [comment] 2015-03-08 20:22
Ok, looking forward. Thanks for info.

**Comment by martec** [comment] 2015-03-16 04:51
1.4.7 released
http://www.sceditor.com/posts/version-1-4-7-released/

**Closed** 2015-03-17 14:20 UTC
Labels: 1.8, bug, p:normal, s:fixed
