### ISSUE TITLE
Can't login in new update

### ISSUE THREAD

**Issue by JAQUBA** [mybb/mybb#1756] opened 2015-01-14 17:46 UTC
"Error
You do not have permissions to run this process. You need administrator permissions to be able to run the upgrade procedure.

If you need to logout, please click here.[...]"

+array_merge(): Argument #1 is not an array - Line: 273 - File: inc/class_session.php
+array_merge(): Argument #1 is not an array - Line: 350 - File: inc/class_session.php

**Comment by Cu8eR** [comment] 2015-01-14 18:31
Please read: https://github.com/mybb/mybb/blob/feature/CONTRIBUTING.md

**Comment by Sama34** [comment] 2015-01-15 03:38
Seems like you don't have administrative rights...?

Can you reproduce this on a fresh install? Can you provide more details please? Otherwise what @Cu8eR mentioned...

**Comment by Destroy666x** [comment] 2015-01-15 11:08
Make sure to include the most important info - steps to reproduce.

I can only confirm the possibility of the mentioned warnings. To avoid them we could define `$usergroup = array();` here: https://github.com/mybb/mybb/blob/feature/inc/functions.php#L1225 but I have no idea why the function doesn't return anything for you. Probably either:
a) there is something wrong with your `usergroups` cache
b) you have wrong values in the `usergroup`/`additionalgroups` columns in the `users` table

**Comment by JAQUBA** [comment] 2015-01-15 17:58
find it out myself ;)
define('MAX_SERIALIZED_INPUT_LENGTH', 65535); in L1914@functions.php

**Comment by Destroy666x** [comment] 2015-01-15 18:25
Then as I said it was damaged `usergroups` cache, thanks for info. Issue for this is here: https://github.com/mybb/mybb/issues/1733

But I'll leave this open due to the missing array definition which could be added.

**Comment by ATofighi** [comment] 2015-01-15 18:30
add to 1.8.4

**Comment by Stefan-ST** [comment] 2015-01-15 20:22
This is low priority, no need to fix it in 1.8.4

**Comment by JN-Jones** [comment] 2015-01-15 20:38
If the change by pirata has the possibility to break caches it's a high priority issue imho. And this a duplicate of #1733 (if it's the only issue here)

**Comment by Stefan-ST** [comment] 2015-01-15 20:52
@JN-Jones Please notice @Destroy666x's comment:
> But I'll leave this open due to the missing array definition which could be added just in case.

#1733 is of course high priority... TBH I don't understand why it has been merged without any testing.

**Closed** 2015-01-25 20:08 UTC
Labels: 1.8, bug, s:fixed
