### ISSUE TITLE
User activity ignored for subscriptions

### ISSUE THREAD

**Issue by Ben-MyBB** [mybb/mybb#4160] opened 2020-10-05 18:44 UTC
There is this check that is supposed to prevent sending notifications to users that haven't been online since they received the last notification.
inc/datahandlers/post.php:
					AND u.lastactive &gt; '{$forum['lastpost']}'However the conditions is always true because &#36;forum['lastpost'] is always 0.

&#36;forum is loaded from datacache which excludes some fields:
		// Things we don't want to cache
		$exclude = array(&quot;unapprovedthreads&quot;, &quot;unapprovedposts&quot;, &quot;threads&quot;, &quot;posts&quot;, &quot;lastpost&quot;, &quot;lastposter&quot;, &quot;lastposttid&quot;, &quot;lastposteruid&quot;, &quot;lastpostsubject&quot;, &quot;deletedthreads&quot;, &quot;deletedposts&quot;);
That causes MyBB to send out way more notifications that it should and may flood users that have subscribed to a popular forum. I'm surprised nobody has complained about this yet.

Original thread: [User activity ignored for subscriptions](https://community.mybb.com/thread-229618.html)

**Comment by yuliu** [comment] 2020-10-06 07:21
Hmm, might be a duplicate of #4106.

**Comment by Stefan-MyBB** [comment] 2020-10-06 07:44
I'm not sure. The proposals to fix that issue are mostly different from this bug.

**Comment by yuliu** [comment] 2020-10-06 08:00
Looks like the discussion is divergent from the problem itself in that issue but the findings seem to be exactly the same as yours:
- The timestamp lastpost of a forum doesn't exist there because the forum variable is pulled from cache where lastpost and some other fields are striped off.

BTW I have several ways to fix this issue, any of them should work but don't know which is better:
1. Add an extra query to get lastpost.
1. Make get_forum() a live version.
1. Use a left join in the final query.

**Closed as completed** 2020-11-06 12:14 UTC
Labels: t:bug, b:1.8, s:resolved
