### ISSUE TITLE
Google's reCaptcha Invisible is not active on login page

### ISSUE THREAD

**Issue by GasmoN** [mybb/mybb#4452] opened 2021-09-15 14:50 UTC
https://community.mybb.com/thread-233524.html
Basically, it is not loading at all and it should, just like on registration page. I thought it's because there is no email3 field at login page, but I did tried changing field name and it still doesn't work.

**Comment by lairdshaw** [comment] 2021-09-15 14:59
Hi there,

Please don't post support issues directly to GitHub. GitHub is for confirmed bugs, as pushed by a team member from the "1.8 Bugs and Issues" forum on the Community Forums. It's great that you've already posted your issue to the General Support forum of the Community Forums. Hopefully you will get the help you need there.

Closing this issue.

**Comment by GasmoN** [comment] 2021-09-15 17:33
Hi, that thread on forum is indeed in support section, but that is actually bug that occurs even with fresh mybb installation so I tought it would be good idea to note that here too.
@lairdshaw

**Comment by lairdshaw** [comment] 2021-09-15 19:30
OK, no worries. Seeing that you can replicate it on a fresh installation, I'll reopen this issue. Perhaps you could separately report it as a bug in the "1.8 Bugs and Issues" forum on the Community Forums, although I won't try to enforce that suggestion seeing that we've already got the issue open here. Just please try to remember next time to report initially there rather than here.

**Comment by chack1172** [comment] 2021-09-21 21:31
In login captcha is only enabled after X amount of failed attempts

**Comment by Sama34** [comment] 2021-09-21 21:33
Seems about correct, this is not a bug but expected behavior :

https://github.com/mybb/mybb/blob/562f147209b951bcd3a31fb1491c7be570a51600/member.php#L1791-L1796

https://github.com/mybb/mybb/blob/562f147209b951bcd3a31fb1491c7be570a51600/member.php#L1871-L1902

**Closed as completed by Sama34** 2021-09-21 21:33 UTC
