### ISSUE TITLE
MyBB attachment downloads corrupted when zlib.output_compression is enabled.

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#292] opened 2014-03-03 19:45 UTC
> This occurs because attachment.php uses an incomplete and/or incorrect method of sending content-range information resulting in the downloaded file having several bytes clipped off the end of the file.
> 
> The man who hosts my server modified the lines affected to resolve this, as well as allow the resuming of paused attachment downloads
> 
> the lines he changed as follows
> 
> replaced  
> `    echo file_get_contents($thumb);`
> 
> with  
> `        header('Accept-Ranges: bytes');<br></br>        header('X-Sendfile: '.$thumb);<br></br>        die;`
> 
> and
> 
> `    header("Content-range: bytes=0-".($attachment['filesize']-1)."/".$attachment['filesize']); <br></br>    echo file_get_contents($mybb->settings['uploadspath']."/".$attachment['attachname']);`
> 
> with  
> `        header('Accept-Ranges: bytes');<br></br>        header('X-Sendfile: '.$mybb->settings['uploadspath'].'/'.$attachment['attachname']);<br></br>        die;`
> 
> he also changed "s to 's to suit his own formatting tastes so changing these is up to your own discretion
> 
> I have seen several reported cases of the attachment corruption with no resolution provided, short of requesting output compression being disabled, which some hosts won't want to do, this resolves the issue correctly. This issue has also occured on other site software

Original report: http://dev.mybb.com/issues/2035
Reporter: Danial Horton
Status: New

**Comment by Cu8eR** [comment] 2016-01-18 21:25
@JN-Jones and others - is it still confirmed? I use zlib.output_compression with latest MyBB 1.8.6 and no issue (and there has not been any for last 1 year with MyBB 1.8.x)

**Comment by Destroy666x** [comment] 2016-01-18 22:54
It was never confirmed and probably will never be due to the lack of details such as compression level. I'll test it tommorow with different levels.

**Comment by Cu8eR** [comment] 2016-01-31 15:07
I tried to confirm this somehow with changing compression level, but without success. I think it could be closed if @Destroy666x wont find anything during his testing

**Comment by Destroy666x** [comment] 2016-01-31 18:52
I tested with:
6 MB .pdf
2 MB .zip
1 MB .jpg
on -1, 1, 5 and 9 compression levels, no problem noticed, so closing.

If anyone has more info, feel free to bump this and provide it.

**Closed by Destroy666x** 2016-01-31 18:52 UTC
Labels: 1.8, bug, s:feedback
