### ISSUE TITLE
undefined variable $usersbrowsing in eval()'d code (92) in ./showthread.php(1617).

### ISSUE THREAD

**Issue by tool-buddy** [mybb/mybb#4602] opened 2022-12-08 12:47 UTC
Issue reproduced under MyBB 1.8.32 and PHP 8.1 and 8.0. Issue does not happen under PHP 7.4
The following warnings appear at the top of the page when loading  thread page.

![image](https://user-images.githubusercontent.com/23341378/206450161-3e5f4125-2874-401b-bb75-10f0b5fdff2b.png)

**Comment by yuliu** [comment] 2022-12-15 16:44
There are 3 PHP "undefined" warnings:

1. undefined array key "allowautourl" in `./inc/class_parser.php`(584).
2. undefined property `MyLanguage::$thread_modes` in eval()'d code (46) in `./showthread.php`(1617).
3. undefined variable `$usersbrowsing` in eval()'d code (92) in `./showthread.php`(1617).

I can't reproduce the 1st & 2nd ones:
 - In the 1st one warning, `allowautourl` is a setting key for "Automatically Parse URLs Into Links", which is introduced in 1.8.27. If you experience this warning, your board may be malfunctioning.
 - The missing `thread_modes` language entry key in the 2nd warning is not found in current code base. It seems the language entry is added and/or used by a plugin or a custom theme/template.

The 3rd one will be fixed shortly.

**Closed as completed** 2023-04-29 14:54 UTC
Labels: t:bug, b:1.8, s:resolved
