### ISSUE TITLE
Merge specific options when moderating with custom tools

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb#265] opened 2014-03-03 19:45 UTC
> When you moderating with the custom moderation tools and you are merging a thread you cannot select any specific options f.e. copy the thread.

Original report: http://dev.mybb.com/issues/1567
Reporter: Michael Malin
Status: Confirmed

**Comment by Destroy666x** [comment] 2016-03-21 16:36
Closing since noone can reproduce (if anyone has more info feel free to bump). Cusrom moderator tools with merge + copy/move/whatever work fine, even when used outside of inline thread moderation (merge is skipped then).

**Closed by Destroy666x** 2016-03-21 16:36 UTC
Labels: s:rejected
